capabilities blacklist
UBC-Thunderbots/Software pull request #1084
Opened 2019-12-05 04:27 UTC by jordanzliu

## Please fill out the following before requesting review on this PR

### Description

make robotcapabilities use a blacklist instead of a whitelist, to improve performance

### Testing Done

existing robot capabiltiies tests pass, tests modified to use blacklist

### Resolved Issues

resolves #1074 

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2019-12-05 04:37 UTC, kelvinkoon submitted a review, later dismissed
LGTM!

2019-12-05 05:04 UTC, jonathanlew requested changes
Looks good, just a nit

2019-12-05 05:04 UTC, jonathanlew commented on src/software/ai/hl/stp/stp_tactic_assignment_test.cpp
> +                                                                                Capability::Chip, Capability::Dribble});
nit: can this be allCapabilities()?

2019-12-05 16:47 UTC, garethellis0 reviewed
LGTM pending Jon's comment

2019-12-05 16:47 UTC, garethellis0 commented on src/software/ai/hl/stp/stp_tactic_assignment_test.cpp
> +                                                                                Capability::Chip, Capability::Dribble});
Agreed, this would be nice.

2019-12-05 23:23 UTC, MathewMacDougall reviewed
LGTM pending Jon's comment

2019-12-06 03:57 UTC, matthewberends reviewed
Nothing to add on top of the existing comments.

2019-12-07 06:14 UTC, MathewMacDougall approved these changes

2019-12-07 07:26 UTC, kelvinkoon approved these changes

2019-12-07 22:50 UTC, jonathanlew approved these changes
:+1:

2019-12-07 22:58 UTC, merged