Added Newer Version Of Valgrind To Software Setup Script
UBC-Thunderbots/Software pull request #1105
Opened 2019-12-24 02:23 UTC by garethellis0

## Please fill out the following before requesting review on this PR

### Description

### Testing Done
Tested out the commands added.

### Resolved Issues

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2019-12-24 07:28 UTC, MathewMacDougall requested changes
Changes look fine. Just clarifying, #1035 is resolved because clion already provides the ability to run under valgrind right? We're not adding our own target?

2019-12-24 07:28 UTC, MathewMacDougall approved these changes

2019-12-24 18:34 UTC, garethellis0 commented
#1035 is resolved because now the version of valgrind installed on peoples computers will properly instrument our debug executables, doesn't have anything to do with CLion.

2019-12-24 20:42 UTC, jonathanlew approved these changes

2019-12-25 21:45 UTC, EvanMorcom approved these changes
LGTM :100:

2019-12-26 17:21 UTC, merged