Geom: Triangle
UBC-Thunderbots/Software pull request #1113
Opened 2020-01-08 20:34 UTC by scveloso

## Please fill out the following before requesting review on this PR

### Description
Small PR to add triangle to shape hierarchy in ```new_geom```

### Testing Done
Added unit tests for triangle

### Resolved Issues
resolves #958

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2020-01-08 20:37 UTC, scveloso commented
A couple of questions/notes:
- Should we prevent construction of degenerate Triangles? Old geom did not do this
- ```center()``` was the only method I saw in-use specifically to Triangles and it is implemented in ```indirect_chip.cpp```, would make it cleaner to move it to ```new_geom```
- Let me know if there are other methods that ```Triangle``` should implement

2020-01-08 23:08 UTC, MathewMacDougall requested changes
New hierarchy is so clean :heart_eyes:. Only comment is maybe we should start breaking shapes out into their own libraries so we don't have a monolithic `new_geom` lib? I think this was brought up in one of @jsn0716 's previous PRs

2020-01-08 23:11 UTC, garethellis0 commented
> Only comment is maybe we should start breaking shapes out into their own libraries so we don't have a monolithic new_geom lib?
:+1: for this

2020-01-08 23:16 UTC, MathewMacDougall commented
> Should we prevent construction of degenerate Triangles? Old geom did not do this
I'm fine not doing this, and I think if we do we'd likely want to do it for all Polygons

> center() was the only method I saw in-use specifically to Triangles and it is implemented in indirect_chip.cpp, would make it cleaner to move it to new_geom
:+1:

> Let me know if there are other methods that Triangle should implement
`center` and `area` are all I think are needed for now

2020-01-08 23:19 UTC, jsn0716 commented
Formatting check seems to be failing, not much else to add to the other comments

2020-01-09 00:36 UTC, scveloso commented
How were you guys thinking of breaking up shapes in their own libraries? Do you mean one directory for each shape? ```new_geom/triangle/triangle.h``` ```new_geom/triangle/triangle.cpp``` ```new_geom/triangle/triangle_test```? I can do it in this PR since its relatively small

2020-01-09 01:32 UTC, jsn0716 requested changes
> How were you guys thinking of breaking up shapes in their own libraries?
> 
> Do you mean one directory for each shape? `new_geom/triangle/triangle.h` `new_geom/triangle/triangle.cpp` `new_geom/triangle/triangle_test`?
> 
> I can do it in this PR since its relatively small

I believe this was meant for the `BUILD` file, to break up the `cc_library` similar to how it was done in #1094

2020-01-09 01:32 UTC, jsn0716 commented on src/scveloso
> +scveloso
Don't think this is meant to be here

2020-01-09 04:22 UTC, MathewMacDougall commented
Yup just different `cc_library` targets for each shape / geometry type, no need for more folders

2020-01-09 22:53 UTC, jonathanlew submitted a review, later dismissed
LGTM!

2020-01-10 05:03 UTC, MathewMacDougall submitted a review, later dismissed
:fire: LGTM

2020-01-10 06:04 UTC, jsn0716 commented
LGTM but CI build is failing

2020-01-10 14:11 UTC, garethellis0 reviewed
LGTM pending CI

2020-01-10 21:00 UTC, scveloso commented
Something went wrong with my linux machine, sorry for the delay on this one

2020-01-12 04:20 UTC, jonathanlew approved these changes

2020-01-12 18:48 UTC, garethellis0 approved these changes
LGTM :+1: :tada:

2020-01-12 20:13 UTC, MathewMacDougall approved these changes

2020-01-12 20:20 UTC, jsn0716 approved these changes

2020-01-12 20:24 UTC, merged