Updated The Navigator To Use New Config Object System
UBC-Thunderbots/Software pull request #1116
Opened 2020-01-10 15:09 UTC by garethellis0

## Please fill out the following before requesting review on this PR

### Description
Start the migration to passing configurations via dependency injection instead of just as global variables. The configuration is now grabbed from the global variable in `full_system_main` and passed through the navigator and the components below it. As such, all the configs in the navigator *should* now be dependency injected. 

Note that the goal of this PR was to be as close to what exists as possible in order to minimize review time. As such, the unit tests still grab the global config instead of their own config, so they are still sensitive to default parameter changes in the yaml.

One thing I'm really no a fan of is the significant nesting in the initializer lists this causes, most notably in `ai.cpp`. Would really appreciate if folks could take a look and think of a slightly more elegant way.

### Testing Done

Unit tests.

### Resolved Issues
Part of https://github.com/UBC-Thunderbots/Software/issues/960

### Length Justification

Configuration changes are fairly wide-reaching, many changes are just renames.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2020-01-12 23:11 UTC, MathewMacDougall requested changes
Seems good overall. One minor question.

2020-01-13 01:43 UTC, garethellis0 commented on src/software/ai/navigator/path_manager/velocity_obstacle_path_manager.cpp
> +            Robot mock_path_robot(0, current_objective.start, initial_path_velocity,
Isn't it embedded in `mock_path_robot`?

2020-01-13 04:14 UTC, jonathanlew requested changes
Overall looks good. Just few minor comments

2020-01-13 04:14 UTC, jonathanlew commented on src/software/ai/navigator/path_manager/velocity_obstacle_path_manager.cpp
> +            Robot mock_path_robot(0, current_objective.start, initial_path_velocity,
yeah this looks ok to me

2020-01-13 21:40 UTC, garethellis0 commented on src/software/ai/ai.h
> +    AI(std::shared_ptr<const AIConfig> config);
changed

2020-01-13 21:40 UTC, garethellis0 commented on src/software/ai/ai_wrapper.h
> +    AIWrapper(std::shared_ptr<const AIConfig> config);
changed

2020-01-13 21:41 UTC, garethellis0 commented on src/software/ai/ai_wrapper.cpp
> +    if (Util::DynamicParameters->getAIControlConfig()->RunAI()->value())
This uses the `AIControl` config, which is different from the `AIConfig`. I agree we should use that here, but I think it's out-of-scope for this PR.

2020-01-14 02:05 UTC, MathewMacDougall commented on src/software/ai/navigator/path_manager/velocity_obstacle_path_manager.cpp
> +            Robot mock_path_robot(0, current_objective.start, initial_path_velocity,
Oh I see we're using the velocity to embed that data. All good

2020-01-14 02:05 UTC, MathewMacDougall reviewed
No other comments from me, just need to CI to pass

2020-01-14 04:08 UTC, jonathanlew submitted a review, later dismissed
LGTM pending CI!

2020-01-14 04:36 UTC, jonathanlew approved these changes
Re-approving...

2020-01-15 05:25 UTC, MathewMacDougall approved these changes

2020-01-15 15:53 UTC, merged