Replaced factories with new templated factory
UBC-Thunderbots/Software pull request #1175
Opened 2020-02-18 02:53 UTC by amrm3lm

## Please fill out the following before requesting review on this PR

### Description

replaced uses of play_factory and backend_factory with the templated generic_factory. 
removed play_factory and backend_factory files. 
renamed generic_factory.cpp to generic_factory.tpp
### Testing Done

everything builds and tests pass
### Resolved Issues

addresses #1143 
### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2020-02-18 17:34 UTC, kelvinkoon reviewed
The formatting test seems to not be passing. Try and run the ./fix_formatting.sh script and it should pass that.

2020-02-19 08:35 UTC, MathewMacDougall requested changes
basically all nit comments, changes themselves look good :+1:

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/corner_kick_play.cpp
> +static TGenericFactory<std::string, Play, CornerKickPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/enemy_freekick_play.cpp
> +static TGenericFactory<std::string, Play, EnemyFreekickPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/example_play.cpp
> +static TGenericFactory<std::string, Play, ExamplePlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/free_kick_play.cpp
> +static TGenericFactory<std::string, Play, FreeKickPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/halt_play.cpp
> +static TGenericFactory<std::string, Play, HaltPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/kickoff_enemy_play.cpp
> +static TGenericFactory<std::string, Play, KickoffEnemyPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/kickoff_friendly_play.cpp
> +static TGenericFactory<std::string, Play, KickoffFriendlyPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/penalty_kick_enemy_play.cpp
> +static TGenericFactory<std::string, Play, PenaltyKickEnemyPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/penalty_kick_play.cpp
> +static TGenericFactory<std::string, Play, PenaltyKickPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/shoot_or_chip_play.cpp
> +static TGenericFactory<std::string, Play, ShootOrChipPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/stop_play.cpp
> +static TGenericFactory<std::string, Play, StopPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/test_plays/halt_test_play.cpp
> +static TGenericFactory<std::string, Play, HaltTestPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/ai/hl/stp/play/test_plays/move_test_play.cpp
> +static TGenericFactory<std::string, Play, MoveTestPlay> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/backend/grsim_backend.cpp
> +static TGenericFactory<std::string, Backend, GrSimBackend> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/backend/radio_backend.cpp
> +static TGenericFactory<std::string, Backend, RadioBackend> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/backend/simulator_backend.cpp
> +static TGenericFactory<std::string, Backend, SimulatorBackend> factory;
nit: missing newline at end of file

2020-02-19 08:35 UTC, MathewMacDougall commented on src/software/util/design_patterns/generic_factory_test.cpp
> +
nit: extra line at top of file

2020-02-21 23:58 UTC, garethellis0 reviewed
Nothing to add beyond Mat's comments.

2020-02-22 00:44 UTC, amrm3lm commented
@MathewMacDougall I've added new lines locally and pushed them, however they dont seem to be reflected in githubs file viewer, but then again no files seem to have a new line at the end when viewed on github?

2020-02-22 01:07 UTC, MathewMacDougall commented
Yea, it's not super obvious but the missing newlines have been pushed. 

GitHub flags missing newlines with a little red arrow in the diff like:
![image](https://user-images.githubusercontent.com/21165407/75083225-7a4ab780-54cc-11ea-9a1e-5fc9d0189e41.png)

And all I'm doing is looking for that marker when I leave the comments. When you pushed your changes to add the newlines, the markers went away.

It's mostly a style thing, but here's why it's generally good to always have newlines at the end of a file (and why GitHub "complains" about it): https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

2020-02-22 01:08 UTC, MathewMacDougall approved these changes
LGTM :+1:

2020-02-22 15:25 UTC, garethellis0 approved these changes
LGTM :+1: :tada:

2020-02-22 19:10 UTC, kelvinkoon approved these changes
LGTM!

2020-02-22 19:58 UTC, merged