Added a Function To Get A T-Value From Arclength In Firmware Polynomial2d
UBC-Thunderbots/Software pull request #1185
Opened 2020-03-01 20:33 UTC by garethellis0

## Please fill out the following before requesting review on this PR

### Description

### Testing Done
Unit tests.

### Resolved Issues
N/A

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2020-03-01 20:48 UTC, EvanMorcom submitted a review, later dismissed
That was fast!

LGTM 🔥

2020-03-01 22:39 UTC, MathewMacDougall requested changes

2020-03-01 22:39 UTC, MathewMacDougall commented on src/firmware/main/math/polynomial_2d_test.cpp
> +    static float t_values[1]                              = {0.5};
Who do these need to be `static`?

2020-03-02 02:27 UTC, garethellis0 commented on src/firmware/main/math/polynomial_2d_test.cpp
> +    static float t_values[1]                              = {0.5};
Whoops, they don't. Removed.

2020-03-02 08:38 UTC, MathewMacDougall approved these changes

2020-03-02 19:04 UTC, EvanMorcom approved these changes
Beauty

2020-03-03 21:32 UTC, merged