Direct velocity primitive class
UBC-Thunderbots/Software pull request #120
Opened 2018-10-31 03:00 UTC by HaomiaoZ

### Description
Create Direct Velocity Primitive class as extension of Primitive class. Similar to move primitive, two types of constructor are created and all the functions in the primitive class are overridden. I follow the comment  style in Move primitive. Leave the comments unchecked as I am not 100% sure whether I follow the appropriate comment style.

### Testing Done
No unit test. Class can be built in CLion.

### Resolved Issues
resolves #91 

### Review Checklist
***It is the reviewers responsibility to also make sure every item here has been covered***
- [ ] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [ ] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x ] **Remove all commented out code**
- [x ] **Remove extra print statements**: for example, those just used for testing
- [x ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2018-11-01 19:04 UTC, MathewMacDougall submitted a review, later dismissed
LGTM :+1: 

Looping in @henrymliu and @EvanMorcom for a second look/sanity check.

2018-11-02 02:08 UTC, EvanMorcom commented
I'm not an expert in the low-level but looks good to me. Only thing I see is the comments at the start of the file are missing.

2018-11-03 06:23 UTC, henryymliu requested changes
Looks good, some minor documentation-related comments.

2018-11-06 05:36 UTC, HaomiaoZ commented on src/thunderbots/software/ai/primitive/direct_velocity_primitive.h
> +     *
definitely, I modified the comment based on the suggestions, would you like to double check?

2018-11-06 20:19 UTC, MathewMacDougall approved these changes
LGTM :+1:

2018-11-08 05:22 UTC, henryymliu submitted a review, later dismissed
LGTM, sorry about the late review.

2018-11-13 21:08 UTC, MathewMacDougall requested changes
@HaomiaoZ it would be great if you could also add some unit tests for this class as well. That will give us test coverage right away, and is a good introduction to testing in our codebase.

You can use #131 as an example. Sorry for the last minute change.

2018-11-14 18:29 UTC, HaomiaoZ commented
Ok, I will work on the unit test over the weekend, need to work on the report right now

2018-11-18 00:29 UTC, HaomiaoZ commented
Add unit tests and get functions for individual parameters in parameters array. Also add some line of code in primitive so that the test could execute. The minor problem with the CmakeList is that all other primitive cpp files need to be included for each test (e.g. need to include move_primitive.cpp under direct velocity primitive test)

2018-11-19 07:45 UTC, MathewMacDougall submitted a review, later dismissed
LGTM :+1: Nice work!

2018-11-19 14:29 UTC, garethellis0 commented on src/thunderbots/software/ai/primitive/direct_velocity_primitive.h
> +     *
I might suggest moving the comment describing the functionality of the entire class to right before we declare the class (ie. on line 9), and leaving just `Creates a new Direct Velocity Primitive` for this function comment.

2018-11-19 15:00 UTC, garethellis0 requested changes
Only comment here is that we've dropped coverage in `primitive.cpp`, because we're not testing the new `if` case we added in the `createPrimitive` function. Adding a quick new unit test in `ai/test/primitive/primitive.cpp` should resolve this.

This slipped by in some other cases, so I've opened a PR (#139) that you can use as a reference. The relevant file is here: https://github.com/UBC-Thunderbots/Software/pull/139/files#diff-1bc8265ff2d89d3a1dc906c996260da7

2018-11-24 20:18 UTC, HaomiaoZ commented
@garethellis0 I add the unit test in `ai/test/primitive/primitive.cpp`. A question is that are we changing function names `getParameterArray()` and `getExtraBitArray()` to `getParameters()` and `getExtraBits()`?

2018-11-24 21:11 UTC, MathewMacDougall commented
@HaomiaoZ we shouldn't be changing the function names, they should match what is in the `primitive.h` files, which is currently `getParameterArray()` and `getExtraBitArray()`

Looks like you'll need to pull from `master` as well to resolve conflicts

2018-11-25 00:00 UTC, garethellis0 commented
@HaomiaoZ - sorry about that, don't worry about changing the function names in this PR. I plan to do that as part of the PR I linked, so I'll also change this primitive once it's merged.

2018-11-25 00:01 UTC, garethellis0 commented
Once you resolve conflicts I think the coverage should automatically update.

2018-11-25 00:31 UTC, HaomiaoZ commented
@garethellis0 @MathewMacDougall  Evan helped me to resolve the conflict. Everything should be good now.

2018-11-25 05:00 UTC, MathewMacDougall approved these changes

2018-11-25 18:07 UTC, garethellis0 commented
Great work, LGTM!

2018-11-25 18:07 UTC, garethellis0 approved these changes

2018-11-25 18:14 UTC, merged