Properly Added Appveyor Badge
UBC-Thunderbots/Software pull request #1213
Opened 2020-03-14 16:56 UTC by garethellis0

## Please fill out the following before requesting review on this PR

### Description

### Testing Done

### Resolved Issues

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2020-03-14 18:35 UTC, MathewMacDougall requested changes

2020-03-14 18:35 UTC, MathewMacDougall commented on README.md
> +[![Build Status](https://ci.appveyor.com/api/projects/status/a7106hhbcal8kqi8/branch/master?svg=true)](https://ci.appveyor.com/project/GarethEllis/software)
Looks like the link to your repo was added accidentally?

2020-03-16 18:07 UTC, EvanMorcom approved these changes
LGTM pending Mat's comment

2020-03-24 16:35 UTC, garethellis0 commented
Closing since we will not have access to the hardware for the forseeable future, and so are using Travis.

2020-03-24 16:35 UTC, closed without merging