Added Radius of Curvature Function to Firmware Polynomial
UBC-Thunderbots/Software pull request #1450
Opened 2020-06-10 00:11 UTC by EvanMorcom

### Description

Added an implementation of calculating the radius of curvature of a polynomial. 

This includes the macro and a few definitions.
### Testing Done

Edge-case unit test and a general test with one 3rd order polynomial

### Review Checklist

- [X] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [X] **Remove all commented out code**
- [X] **Remove extra print statements**: for example, those just used for testing
- [X] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [X] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2020-06-10 01:00 UTC, jonathanlew submitted a review, later dismissed
Assuming this is copied from trajectory planner and will replace that code when that PR is merge, then LGTM!

2020-06-10 01:14 UTC, EvanMorcom commented
> Assuming this is copied from trajectory planner and will replace that code when that PR is merge, then LGTM!

Yep, I'm just breaking this one out 👍

2020-06-10 02:21 UTC, MathewMacDougall submitted a review, later dismissed

2020-06-10 03:45 UTC, garethellis0 requested changes

2020-06-10 19:50 UTC, MathewMacDougall approved these changes

2020-06-11 03:28 UTC, akhilveeraghanta approved these changes
LGTM :fire:

2020-06-11 04:31 UTC, garethellis0 commented on src/firmware/shared/math/polynomial_2d.c
> +                    2),                                                                  \
Yeah, sorry, your final interpretation was correct.

2020-06-11 04:31 UTC, garethellis0 approved these changes
LGTM :+1: :tada:

2020-06-11 19:08 UTC, merged