Mathew/move static field constructor
UBC-Thunderbots/Software pull request #1472
Opened 2020-06-14 18:39 UTC by MathewMacDougall

## Please fill out the following before requesting review on this PR

### Description

Moved the `::TestUtil::createSSLDivBField()` function to the `Field` as a static constructor. Doing this now because I realized I need it there in order to use in the simulated test library / text fixture target (because it's not a `cc_test` and so I can't depend on `test_util` because it's marked as `test_only=True`)

### Testing Done

Added more checks to the creation unit test. Now all "getter" functions of the field are covered.

### Resolved Issues

resolves #1400 

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2020-06-14 18:44 UTC, jonathanlew reviewed
Can we quickly add div A field too?

2020-06-15 00:21 UTC, garethellis0 requested changes
I'd really like to avoid this change if possible, since the specific dimensions of the SSL Div B field don't seems like they belong in the generic field class. Perhaps let's mark the test fixture stuff as `test_only` as well? That _should_ work.

2020-06-15 05:18 UTC, MathewMacDougall commented
> I'd really like to avoid this change if possible, since the specific dimensions of the SSL Div B field don't seems like they belong in the generic field class.

I don't see why not? `Angle` has constructors for `zero`, `half`, etc. angles which is similar (not 100% same comparison).


> Perhaps let's mark the test fixture stuff as test_only as well? That should work.

True I also completely did not think of that.

2020-06-15 21:55 UTC, MathewMacDougall commented
Ok I left the `DivB` field constructor back in `TestUtil` but improved the unit test. I also added a function and test for creating a Division A field @jonathanlew

2020-06-15 22:06 UTC, jonathanlew commented on src/software/test_util/test_util_test.cpp
> +
nit extra new line

2020-06-15 22:25 UTC, MathewMacDougall commented on src/software/test_util/test_util_test.cpp
> +
removed

2020-06-15 22:45 UTC, jonathanlew approved these changes
LGTM! :field_hockey:

2020-06-16 00:09 UTC, kelvinkoon approved these changes

2020-06-16 00:52 UTC, akhilveeraghanta approved these changes
⚽

2020-06-16 05:06 UTC, garethellis0 approved these changes

2020-06-16 05:07 UTC, merged