Finalize module interfaces
UBC-Thunderbots/Software pull request #18
Opened 2018-08-04 20:08 UTC by MathewMacDougall

This is a continuation of #15 but with the commits cleaned up a bit so it should be easier to review. The first two commits deal with all the file moves and renames, so all the important stuff is in the third commit and later. It is easiest to view by viewing one commit at a time.

resolves #8 and #6

2018-08-04 20:50 UTC, jordanzliu commented on src/thunderbots/software/ai/world/world.h
> +    // We leave these members public to make theme easy to access and update, rather
typo - ~~theme~~ -> them

2018-08-04 21:00 UTC, jordanzliu commented on src/thunderbots/software/ai/navigator/rrt/rrt.cpp
> +            std::unique_ptr<Primitive> move_prim =
Would it be good to move logic specific to each primitive into its own function that takes a single Intent and returns a Primitive?

2018-08-04 21:52 UTC, henryymliu requested changes

2018-08-04 21:52 UTC, henrymliu commented on src/thunderbots/software/ai/navigator/rrt/rrt.cpp
> +                std::unique_ptr<Primitive>(new MovePrimitive(
`std::make_unique` would probably make this statement a lot shorter

2018-08-04 21:52 UTC, henrymliu commented on src/thunderbots/software/ai/navigator/rrt/rrt.cpp
> +            std::cerr << "Error: Unrecognized Intent given to navigator" << std::endl;
i personally recommend wiping the hard drive and setting the computer on fire instead of an exception

2018-08-04 21:54 UTC, henrymliu commented
Also, I notice the removal of the robot filter stuff; what's the reason for that?

2018-08-05 00:44 UTC, MathewMacDougall commented
I removed "placeholder" implementations for stuff that didn't really need to be there, since the interfaces were changing and the data structure I had started with were not necessarily the most applicable anymore. I didn't want to bias anyone that would be working on it next.

2018-08-05 01:03 UTC, garethellis0 requested changes
I'm actually really happy with this. It might look like I've made a lot of comments, but it's not too many given the sheer amount of code here. There are a few items (like relative includes) for which resolving all instances should pretty quickly clear a bunch of comments.

2018-08-05 01:03 UTC, garethellis0 commented on src/thunderbots/shared_util/constants.h
> +static const std::string AI_PRIMITIVES_TOPIC               = "backend/enemy_team";
Does firmware need to know about these constants? If not we should put them in the software folder. Either way, I don't think we'll be able to build in `std::string` to firmware, so these will probably have to change.

2018-08-05 03:40 UTC, MathewMacDougall commented on src/thunderbots/software/ai/primitive/primitive.cpp
> +    }
This is the superclass.

2018-08-05 03:40 UTC, MathewMacDougall commented on src/thunderbots/software/ai/primitive/primitive.cpp
> +    }
This is the superclass

2018-08-05 06:02 UTC, MathewMacDougall commented on src/thunderbots/software/backend_input/message_util.cpp
>      team_msg.robots.clear();
It should be I think I was just being extra explicit while testing this initially.

2018-08-05 16:43 UTC, garethellis0 commented on src/thunderbots/software/ai/world/ball.h
> +    void update(Point &new_position, Vector2 &new_velocity);
We should call `Vector2` `Vector` or `Vector2d`. `Vector2` makes it should like it's the second version of the `Vector` class.

2018-08-05 17:54 UTC, garethellis0 submitted a review, later dismissed

2018-08-05 21:26 UTC, henryymliu submitted a review, later dismissed

2018-08-05 23:59 UTC, MathewMacDougall commented
Any last comments? I'd like to get this merged tonight?

2018-08-06 01:57 UTC, jordanzliu approved these changes

2018-08-06 01:59 UTC, merged