Add command line args for enableVisualizer() on SimulatedTests
UBC-Thunderbots/Software pull request #1825
Opened 2020-11-14 22:11 UTC by itsarune

## Please fill out the following before requesting review on this PR

### Description

- Added a custom gtest main that is run whenever simulated tests run
- updated the build files and replaced references to standard main to the new one
- added a yaml so that we can pass in `--enable_visualizer` on the command line

There are two ways to run the tests in the visualizer:
1. `bazel test //software/simulated_tests:some-target --test-arg="--enable_visualizer"`
2. `bazel run //software/simulated_tests:some-target -- --enable_visualizer`

Running without the flag runs the test normally.

### Testing Done

- current tests pass
- verified that the `--enable_visualizer` flag works for all tests
- there is a known error with free-kick-play when running `--enable_visualizer` on it

### Resolved Issues

resolves #1751

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2020-11-15 01:06 UTC, akhilveeraghanta reviewed
Tested locally, works really well for me, nice work! :100:

2020-11-15 01:38 UTC, jonathanlew requested changes
Good work. It would be nice to put the commands in `docs/getting-started.md` as well

2020-11-18 03:46 UTC, jared-paul reviewed
LGTM aside from Jon's comment, I agree with adding it to SimulatedTestFixture. Will reapprove once that's done

2020-11-21 04:20 UTC, itsarune commented on src/software/simulated_tests/corner_kick_play_test.cpp
> +    }
added!

2020-11-21 18:17 UTC, jonathanlew submitted a review, later dismissed
LGTM pending fix formatting

2020-11-21 19:42 UTC, jonathanlew approved these changes, later dismissed

2020-11-23 23:01 UTC, akhilveeraghanta approved these changes, later dismissed
💯

2020-11-28 03:07 UTC, jonathanlew approved these changes
LGTM!

2020-11-28 03:21 UTC, akhilveeraghanta approved these changes

2020-11-28 03:27 UTC, merged