Simulated Action Tests
UBC-Thunderbots/Software pull request #1881
Opened 2020-12-30 00:19 UTC by jonathanlew

## Please fill out the following before requesting review on this PR

### Description
* Added SimulatedActionTestFixture 
* Added SimulatedMoveActionTest
* Support visualization

### Testing Done
example move action test

### Resolved Issues
resolves https://github.com/UBC-Thunderbots/Software/issues/1870

### Length Justification
just over

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2020-12-30 17:19 UTC, MathewMacDougall requested changes
Overall LGTM.

Because the `SimulatedActionTestFixture` specifies what navigator/path planner it's using, it could diverge from what is used in STP/for gameplay. Just want to double check this is intended, and that the purpose of these tests will more be for action logic rather that doesn't rely on navigator specifics? I'd still imagine there may be cases where you want to make sure an `InterceptAction` actually is able to intercept the ball with the navigator that would be useful for gameplay. In theory if the robots couldn't intercept the ball after a navigator change the SimulatedPlayTests would catch it, but I'd imagine we'd have better coverage of each Action in these tests, so this would be the more likely place to rely on to catch those issues.

2021-01-01 02:53 UTC, garethellis0 reviewed
Nothing much to add on top of Mathew here

2021-01-01 02:53 UTC, garethellis0 commented on src/software/simulated_tests/validation_functions/robot_at_position_validation.h
> + * @param close_to_destination_threshold The threshold where the robot is considered close
It's probably worth adding units to this.

2021-01-10 16:45 UTC, jonathanlew commented
closed due to FSM project

2021-01-10 16:45 UTC, closed without merging