Joshua/fixing inconsistent naming
UBC-Thunderbots/Software pull request #1885
Opened 2021-01-07 04:29 UTC by JoshuaWu7

## Please fill out the following before requesting review on this PR

### Description

Refactors the inconsistent naming based on code style. Refer to ticket on refactored code.

### Testing Done

### Resolved Issues

resolves #1800 

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-01-09 06:54 UTC, jonathanlew requested changes
Going in the right direction, but there are a few issues

2021-01-09 06:54 UTC, jonathanlew commented on docs/software-architecture-and-design.md
> +    * [GameState](#game_state)
please check that the link still works

2021-01-09 06:54 UTC, jonathanlew commented on src/software/ai/evaluation/BUILD
> +    hdrs = ["deflectOffEnemyTarget.h"],
file names follow snake_case, so please don't change this

2021-01-09 06:54 UTC, jonathanlew commented on src/software/ai/evaluation/BUILD
> +        ":deflectOffEnemyTarget",
same here

2021-01-09 06:54 UTC, jonathanlew commented on src/software/ai/hl/stp/tactic/shadow_freekicker_tactic.h
> +     * slightly to the left of the vector from the enemy free_kicker to the friendly goal
where there are comments like here, we should use a space
```suggestion
     * slightly to the left of the vector from the enemy free kicker to the friendly goal
```

2021-01-09 06:54 UTC, jonathanlew commented on src/software/gui/full_system/widgets/ai_control.cpp
> +<<<<<<< HEAD
these are merge conflict markers and these need to be cleaned up

2021-01-11 20:20 UTC, kelvinkoon requested changes

2021-01-11 20:20 UTC, kelvinkoon commented on .vscode/settings.json
> +}
EOF/new line needed at the end of every file.

2021-01-14 04:31 UTC, JoshuaWu7 commented on docs/software-architecture-and-design.md
> +    * [GameState](#game_state)
Link is still working

2021-01-16 23:25 UTC, JoshuaWu7 commented on src/software/simulated_tests/BUILD
> +<<<<<<< HEAD
Merge conflict markers

2021-01-17 00:14 UTC, JoshuaWu7 commented on src/software/gui/full_system/widgets/ai_control.h
> + * @param widget The widget containing the ComboBox to set up
Merge conflict

2021-01-17 00:15 UTC, JoshuaWu7 commented on src/software/gui/full_system/widgets/ai_control.cpp
> +<<<<<<< HEAD
Merge conflict

2021-01-21 04:23 UTC, jordanzliu reviewed
LGTM other than merge conflict markers

2021-01-24 06:24 UTC, jonathanlew requested changes
looks like you need to run fix formatting: https://github.com/UBC-Thunderbots/Software/blob/master/docs/workflow.md#formatting-your-code 

other than that, just a few nits

2021-01-24 06:24 UTC, jonathanlew commented on src/software/gui/full_system/widgets/ai_control.h
> + * @param current_game_state_parameter The parameter that holds the current game_state
```suggestion
 * @param previous_game_state_parameter The parameter that holds the previous game state
 * @param current_game_state_parameter The parameter that holds the current game state
```

2021-01-24 06:24 UTC, jonathanlew commented on src/software/ai/motion_constraint/motion_constraint_set_builder_test.cpp
> +    // sets of motion constraints for each type of game_state
```suggestion
    // sets of motion constraints for each type of game state
```

2021-01-24 06:24 UTC, jonathanlew commented on src/software/ai/motion_constraint/motion_constraint_set_builder.h
> + * game_state
```suggestion
 * game state
```

2021-01-24 06:24 UTC, jonathanlew commented on src/software/ai/hl/stp/tactic/shadow_free_kicker_tactic_test.cpp
> +     * whether the robot is  blocking the free_kick from left or right
```suggestion
     * whether the robot is  blocking the free kick from left or right
```

2021-01-24 06:24 UTC, jonathanlew commented on src/software/ai/hl/stp/tactic/shadow_free_kicker_tactic_test.cpp
> +     * whether the robot is  blocking the free_kick from left or right
```suggestion
     * whether the robot is  blocking the free kick from left or right
```

2021-01-24 06:24 UTC, jonathanlew commented on src/software/ai/hl/stp/tactic/shadow_free_kicker_tactic.h
> +                      // free_kick (with a buffer factor)
```suggestion
                      // free kick (with a buffer factor)
```

2021-01-28 22:15 UTC, jonathanlew approved these changes
LGTM!

2021-01-28 23:52 UTC, kelvinkoon approved these changes

2021-01-29 00:34 UTC, merged