Log full filtered world state as SSL_WrapperPacket
UBC-Thunderbots/Software pull request #1900
Opened 2021-01-17 02:10 UTC by jordanzliu

## Please fill out the following before requesting review on this PR

### Description

Log full filtered world state as SSL_WrapperPacket

### Testing Done

Unit tests

### Resolved Issues

Resolves #1898 

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-01-17 07:09 UTC, jonathanlew requested changes
looks good just a nit

2021-01-17 07:09 UTC, jonathanlew commented on src/software/proto/message_translation/ssl_wrapper.cpp
> +    const World& world, bool friendly_team_colour_yellow)
we have a TeamColour enum that you can use

2021-01-18 00:16 UTC, jonathanlew approved these changes
LGTM!

2021-01-18 03:55 UTC, kelvinkoon approved these changes
💯

2021-01-18 04:17 UTC, merged