Add autokick/chip and max allowed speed to MoveIntent/Primitive
UBC-Thunderbots/Software pull request #1966
Opened 2021-02-27 07:51 UTC by jonathanlew

## Please fill out the following before requesting review on this PR

### Description
* adds a way to set a top speed for the robots
* adds a way to chip or kick using the moveintent/primitive

### Testing Done
unit testing

### Resolved Issues
resolves #1959 
part of #1882

### Length Justification
hard to pull these changes apart

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-02-27 16:09 UTC, akhilveeraghanta requested changes
nice yeetage of code

2021-02-28 08:18 UTC, jonathanlew commented on src/software/ai/hl/stp/tactic/move/move_tactic.h
> +        std::optional<TbotsProto::Autochipkick> autochipkick = std::nullopt);
changed to union

2021-02-28 08:18 UTC, jonathanlew commented on src/shared/proto/primitive.proto
> +message Autochipkick
changed to AutoChipOrKick

2021-02-28 08:18 UTC, jonathanlew commented on src/software/proto/primitive/primitive_msg_factory.cpp
> +            return ROBOT_MAX_SPEED_METERS_PER_SECOND;
logged warning

2021-02-28 08:18 UTC, jonathanlew commented on src/shared/constants.h
> +// The max allowed speed of the robot when the stop command is issued, in metres per
ok

2021-02-28 17:39 UTC, akhilveeraghanta approved these changes
LGTM :+1:

2021-02-28 20:58 UTC, jsn0716 approved these changes
LGTM 👍

2021-02-28 21:06 UTC, merged