Add reset view function and button
UBC-Thunderbots/Software pull request #1979
Opened 2021-03-07 08:04 UTC by BrianS99

## Please fill out the following before requesting review on this PR

### Description
Added a Reset View button that can be accessed using context menu on simulator field (right-click)

### Testing Done
Since applies to visual simulator only, tested by running the standalone simulator as well full simulator

### Resolved Issues
Resolves #1553

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-03-08 16:47 UTC, akhilveeraghanta requested changes
it works really well! super useful feature :fire: nice work

just a couple comments from my end

2021-03-08 16:47 UTC, akhilveeraghanta commented on src/software/gui/generic_widgets/draw_function_visualizer/draw_function_visualizer.cpp
> +    {
why doesn't `fitInView` work the first time?

2021-03-08 16:47 UTC, akhilveeraghanta commented on src/software/gui/standalone_simulator/widgets/standalone_simulator_draw_function_visualizer.cpp
> +    menu.addAction("Reset View", resetViewAction);
can we just use `resetView` here? do we need the create function?

2021-03-08 16:47 UTC, akhilveeraghanta commented on src/software/gui/generic_widgets/draw_function_visualizer/draw_function_visualizer.h
> +
nit: you can remove this comment, we usually don't talk about subclasses in the parent class

2021-03-08 16:47 UTC, akhilveeraghanta commented on src/software/gui/generic_widgets/draw_function_visualizer/draw_function_visualizer.h
> +     * lastViewArea} as reference
nit: java doc needs a @param

2021-03-10 05:43 UTC, jonathanlew reviewed
Nothing to add beyond what's already been said

2021-03-14 03:46 UTC, BrianS99 commented
Hi @akhilveeraghanta, I put the function in the context menu function, and I cleaned up the nits. We originally thought that we needed to call `fitInView` many times, but turns out we just need to call it once to work here

Tested again with the simulators, works well

2021-03-15 03:50 UTC, itsarune submitted a review, later dismissed
👍👍

2021-03-15 08:21 UTC, jonathanlew requested changes
just one nit

2021-03-20 17:52 UTC, akhilveeraghanta commented
nothing to add beyond existing comments

2021-03-20 23:07 UTC, jonathanlew approved these changes

2021-03-22 13:36 UTC, akhilveeraghanta approved these changes
lgtm :fire:

2021-03-27 08:07 UTC, merged