Implemented Velocity Wheel Trajectory Follower
UBC-Thunderbots/Software pull request #2062
Opened 2021-05-09 17:02 UTC by jonathanlew

## Please fill out the following before requesting review on this PR

### Description
* Implemented Velocity Wheel Trajectory Follower
* Adjusted the interfaces slightly to add num_elements
* Added setTargetRPM for clarity

### Testing Done
pending

### Resolved Issues
resolves #1649 
resolves #2044

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-05-09 18:00 UTC, kelvinkoon requested changes
LGTM! Just 1 nit.

2021-05-09 18:40 UTC, jsn0716 submitted a review, later dismissed
LGTM pending Kelvin's comment

2021-05-09 22:06 UTC, akhilveeraghanta approved these changes, later dismissed
lgtm :100:

2021-05-09 23:10 UTC, jonathanlew commented on src/firmware/app/world/velocity_wheel.h
>   *
fixed

2021-05-10 06:41 UTC, kelvinkoon approved these changes

2021-05-10 07:41 UTC, jsn0716 approved these changes

2021-05-10 17:12 UTC, akhilveeraghanta approved these changes

2021-05-10 18:23 UTC, merged