implemented isAppllicable and inVariant test to KickoffFriendlyPlay
UBC-Thunderbots/Software pull request #2277
Opened 2021-10-09 20:53 UTC by piramonpan

## Please fill out the following before requesting review on this PR

### Description

Added tests for isApplicable and invariantHold test to KickoffFriendlyPlay function

### Testing Done

Unit test 

### Resolved Issues

resolves #2257 

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-10-10 14:19 UTC, akhilveeraghanta requested changes
Nice work on the test! 

There seems to be two other files that made it in, you can undo the changes, make a new commit and push it up (git add, git commit, git push)

2021-10-10 14:19 UTC, akhilveeraghanta commented on src/.bazelproject
> +
nit: seems to be some extra lines here

2021-10-10 14:19 UTC, akhilveeraghanta commented on src/cc_toolchain/wrapper/linux_gcc
> +exec /usr/bin/gcc-7 -Wl,--no-as-needed "$@"
Ah this was an issue from a while back, you can remove the -7, its fixed on master

2021-10-11 19:46 UTC, jonathanlew reviewed
nothing to add beyond existing comments, looks good

2021-10-21 02:42 UTC, jonathanlew submitted a review, later dismissed
lgtm pending ci

2021-10-23 19:25 UTC, LiCody commented on src/software/ai/hl/stp/play/kickoff_friendly_play_test.cpp
> +// hi
nit: we can probably remove these two lines
Also you can run ./formatting_scripts/fix_formatting,sh from the software folder to fix formatting check from failing

2021-11-12 01:55 UTC, jonathanlew reviewed
just a nit

2021-11-12 01:55 UTC, jonathanlew commented on src/software/ai/hl/stp/play/kickoff_friendly_play_test.cpp
> +    // hi
please remove this random comment

2021-11-14 04:28 UTC, jonathanlew approved these changes
LGTM!

2021-11-15 17:03 UTC, akhilveeraghanta approved these changes

2021-11-18 20:24 UTC, LiCody approved these changes

2021-11-20 20:05 UTC, merged