Enemy Ball Placement Play + New Motion Constraint Validation Function
UBC-Thunderbots/Software pull request #2279
Opened 2021-10-09 22:31 UTC by PhilD71

## Please fill out the following before requesting review on this PR

### Description

This PR adds the Enemy Ball Placement Play used at Robocup 2021, now with proper validation functions to check that robots never enter the motion constraint created by ball placement. With this, a new non terminating validation function is introduced, `robotsNotViolatingMotionConstraints`. 
### Testing Done
Simulated tests written

### Resolved Issues

#1999 
### Length Justification

Its all one play + necessary adjustments to provide support for the new simulated tests
### Review Checklist

All done!
**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-10-10 14:11 UTC, akhilveeraghanta requested changes
Nice work! Just got a couple nits

2021-10-10 14:11 UTC, akhilveeraghanta commented on src/software/ai/hl/stp/play/enemy_ball_placement_play.h
> +     * @param yield yield
slight nit: order of params doesn't match the function

2021-10-10 14:11 UTC, akhilveeraghanta commented on src/software/simulated_tests/non_terminating_validation_functions/robots_violating_motion_constraint.h
> + * @param yield yields control to the next routine (coroutines) with error message
nit: missing obstacle_factory and constraints params

2021-10-10 14:11 UTC, akhilveeraghanta commented on src/software/ai/hl/stp/play/enemy_ball_placement_play_test.cpp
> +}
These test seem to be the same code with just the ball position changing, you could reduce this down to 1 parameterized test

Checkout `simulated_chip_tactic_test.cpp` for an example, you can parameterize on the ball position

2021-10-11 20:10 UTC, jonathanlew reviewed
just a few comments

2021-10-11 20:10 UTC, jonathanlew commented on src/software/ai/hl/stp/play/enemy_ball_placement_play.cpp
> +                                              ROBOT_MAX_RADIUS_METERS * 3);
how do we know there will be 2 enemy threats?

2021-10-11 20:10 UTC, jonathanlew commented on src/software/ai/hl/stp/play/enemy_ball_placement_play_test.cpp
> +}
agreed, I'll re-review once it's cleaned up

2021-10-11 20:10 UTC, jonathanlew commented on src/software/geom/polygon.cpp
> +Polygon Polygon::expand(double expansion_amount) const
is there a test for this new function?

2021-10-16 19:24 UTC, PhilD71 commented on src/software/ai/hl/stp/play/enemy_ball_placement_play.cpp
> +                                              ROBOT_MAX_RADIUS_METERS * 3);
Typo - should be 0, fixed in next commit

2021-10-16 20:04 UTC, PhilD71 commented on src/software/geom/polygon.cpp
> +Polygon Polygon::expand(double expansion_amount) const
the tests got messed up when I untangled the branch from robocup 2021 - I have the new tests in now

2021-10-18 18:37 UTC, jonathanlew requested changes
looks good, just one comment

2021-10-18 18:37 UTC, jonathanlew commented on src/software/simulated_tests/simulated_play_test_fixture.h
> +    std::shared_ptr<AiConfig> getAiConfig();
we shouldn't expose non-const pointers so it doesn't get modified elsewhere, i.e. the function signature should be `const std::shared_ptr<const AiConfig> getAiConfig() const`

2021-10-20 17:13 UTC, jonathanlew commented on src/software/simulated_tests/simulated_play_test_fixture.h
> +    std::shared_ptr<AiConfig> getAiConfig() const;
same comment as before, the function signature should be `const std::shared_ptr<const AiConfig> getAiConfig() const`

2021-10-23 02:37 UTC, akhilveeraghanta reviewed
got nothing much to add beyond the existing comments, lgtm!

2021-10-28 02:47 UTC, PhilD71 commented on src/software/simulated_tests/simulated_play_test_fixture.h
> +    std::shared_ptr<AiConfig> getAiConfig() const;
oops should be fixed now

2021-10-28 02:49 UTC, jonathanlew approved these changes
LGTM!

2021-10-28 02:59 UTC, akhilveeraghanta approved these changes

2021-10-28 03:18 UTC, merged