Log a warning when a play has isApplicable() as true and invariantHolds() as false
UBC-Thunderbots/Software pull request #2280
Opened 2021-10-09 22:55 UTC by JoshWong16

## Please fill out the following before requesting review on this PR

### Description

Log a warning when play::isApplicable() is true and play::invariantHolds() is false. Meant to detect unwanted behaviour.

### Testing Done

Manual testing using AI vs AI and forcing invariantHolds() to be false. The new warning appeared when it was supposed to. 

### Resolved Issues

https://github.com/UBC-Thunderbots/Software/issues/2248

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-10-10 14:24 UTC, akhilveeraghanta reviewed
LGTM :100:! Looks like you just need to run `fix_formatting.sh` in the `environment_setup` folder

2021-10-11 05:19 UTC, jonathanlew requested changes

2021-10-11 05:19 UTC, jonathanlew commented on src/software/ai/hl/stp/stp.cpp
> +                LOG(WARNING) << "Play::isApplicable() is true and Play::invariantHolds() is false"
please also print the name of the play with `objectTypeName(*play)`

2021-10-11 05:19 UTC, jonathanlew commented
Please also change the name of the PR to be more descriptive

2021-10-12 05:02 UTC, jonathanlew approved these changes
LGTM!

2021-10-17 04:22 UTC, akhilveeraghanta approved these changes

2021-10-23 19:21 UTC, merged