Implemented CornerKickPlay testcases for invariantHolds() and isApplicable()
UBC-Thunderbots/Software pull request #2286
Opened 2021-10-12 05:53 UTC by Joshuayellowley

## Please fill out the following before requesting review on this PR

### Description

Created test cases for invariantHolds() and isApplicable() functions for CornerKickPlay.  These tests are implemented using a parameterized test with varying ball positions, team possessions, and referee commands.

These tests all pass when running 
`bazel test //software/ai/hl/stp/play:corner_kick_play_test`

### Testing Done

This PR added additional tests

### Resolved Issues

resolves #2259 

### Length Justification

n/a

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-10-12 15:36 UTC, akhilveeraghanta submitted a review, later dismissed
Really nice work on the tests :fire: LGTM!

2021-10-14 16:17 UTC, jonathanlew requested changes
cool use of TEST_P, just a couple comments

2021-10-14 16:17 UTC, jonathanlew commented on src/software/ai/hl/stp/play/corner_kick_play_test.cpp
> +    {
you can do `EXPECT_EQ(corner_kick_play.isApplicable(world), std::get<5>(GetParam()))`

2021-10-14 16:17 UTC, jonathanlew commented on src/software/ai/hl/stp/play/corner_kick_play_test.cpp
> +    BallState ball_state_in_corner(std::get<3>(GetParam()), std::get<4>(GetParam()));
`std::get<4>(GetParam())` isn't necessary since it's always `Vector (0,0)`, so remove that 4th param and do
```suggestion
    BallState ball_state_in_corner(std::get<3>(GetParam()), Vector(0,0));
```

2021-10-21 16:13 UTC, Joshuayellowley commented on src/software/ai/hl/stp/play/corner_kick_play_test.cpp
> +    {
Should be updated now.

2021-10-21 16:13 UTC, Joshuayellowley commented on src/software/ai/hl/stp/play/corner_kick_play_test.cpp
> +    BallState ball_state_in_corner(std::get<3>(GetParam()), std::get<4>(GetParam()));
Should be updated now.

2021-10-27 19:48 UTC, jonathanlew approved these changes
LGTM!

2021-11-01 06:52 UTC, xyztiger approved these changes
LGTM! nice work :)

2021-11-06 22:26 UTC, merged