Test invariantHolds and isApplicable for enemy penalty.
UBC-Thunderbots/Software pull request #2288
Opened 2021-10-16 06:19 UTC by jpatch22

## Please fill out the following before requesting review on this PR

### Description

### Testing Done

### Resolved Issues

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-10-23 02:41 UTC, akhilveeraghanta requested changes
just 1 comment, other than that looks good to me!

make sure to run fix_formatting.sh as well

2021-10-23 02:41 UTC, akhilveeraghanta commented on src/software/ai/hl/stp/play/penalty_kick_enemy_play_test.cpp
> +    // pass it in.
These comments in the example were mostly to explain what was going on
you can remove them from this file (maybe just keep a couple that explain the test)

2021-10-23 19:34 UTC, LiCody submitted a review, later dismissed

2021-10-23 20:03 UTC, Joshuayellowley requested changes

2021-10-23 20:03 UTC, Joshuayellowley commented on src/software/ai/hl/stp/play/penalty_kick_enemy_play_test.cpp
> +TEST(HaltPlayInvariantAndIsApplicableTest, test_invariant_and_is_applicable)
Just one thing, is the "HaltPlayInvariantAndIsApplicableTest" the correct test Hierarchy here?  I'm not sure if it is needed functionally but I think it might be better for legibility if it was related to EnemyPenalty

2021-10-27 02:59 UTC, LiCody commented on src/software/ai/hl/stp/play/penalty_kick_enemy_play_test.cpp
> +TEST(HaltPlayInvariantAndIsApplicableTest, test_invariant_and_is_applicable)
Generally the test suite name(The first parameter) is set to the name of the file in camelcase. So in this case it would be PenaltyKickEnemyPlayTest

2021-10-27 05:04 UTC, jonathanlew reviewed
just one non-blocking comment, otherwise it should be good to go

2021-10-27 05:04 UTC, jonathanlew commented on src/software/ai/hl/stp/play/penalty_kick_enemy_play_test.cpp
> +        RefereeCommand::PREPARE_PENALTY_THEM, RefereeCommand::PREPARE_PENALTY_THEM));
I'd like to see a test for normal_start (since that's a natural transition) and for prepare_penalty_us (as a sanity check) as well.

2021-11-07 04:09 UTC, jonathanlew submitted a review, later dismissed
LGTM!

2021-11-14 04:31 UTC, jonathanlew approved these changes

2021-11-14 04:54 UTC, Joshuayellowley approved these changes

2021-11-22 21:42 UTC, akhilveeraghanta approved these changes

2021-11-25 19:56 UTC, merged