Added test for invariantHolds and IsApplicable for shoot or pass play
UBC-Thunderbots/Software pull request #2291
Opened 2021-10-16 20:33 UTC by Bvasilchikov

## Please fill out the following before requesting review on this PR

### Description

this PR implements tests for `invariantHolds` and `isApplicable` in `ShootOrPassPlay`

### Testing Done

 `bazel build //software/ai/hl/stp/play:shoot_or_pass_play_test`
 `bazel test //software/ai/hl/stp/play:shoot_or_pass_play_test`

### Resolved Issues

resolves #2260

### Length Justification

n/a

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-10-23 02:43 UTC, akhilveeraghanta approved these changes
lgtm!

2021-10-23 02:43 UTC, akhilveeraghanta requested changes
ah woops just realized CI is failing, make sure to run `formatting_scripts/fix_formatting.sh`

2021-10-27 05:02 UTC, jonathanlew reviewed
just one non-blocking comment

2021-10-27 05:02 UTC, jonathanlew commented on src/software/ai/hl/stp/play/shoot_or_pass_play_test.cpp
> +        ::TestUtil::createGameState(RefereeCommand::FORCE_START, RefereeCommand::HALT));
can we also have a test for one of the special game states like PREPARE_KICKOFF_US

2021-11-14 04:30 UTC, jonathanlew approved these changes
LGTM!

2021-11-14 05:15 UTC, iammie9 approved these changes

2021-11-15 17:20 UTC, akhilveeraghanta approved these changes
lgtm!

2021-11-20 19:08 UTC, merged