EnemyFreeKickPlay isApplicable and invariantHolds tests
UBC-Thunderbots/Software pull request #2292
Opened 2021-10-16 20:52 UTC by iammie9

## Please fill out the following before requesting review on this PR

### Description

  Created a blank world to test the play EnemyFreeKick. Implemented isApplicable and invariantHolds tests for the play.

### Testing Done

 unit test

### Resolved Issues

 resolves issue #2261

### Length Justification

 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ x] **Remove all commented out code**
- [ x] **Remove extra print statements**: for example, those just used for testing
- [x ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-10-19 21:42 UTC, jameschuang2002 requested changes
I think you need to run the formatting script. I am also not sure whether you should change NORMAL_START to DIRECT_FREE_US to pass the gameplay test. I reach this conclusion after reading similar documents about isApplicable and invariantHolds tests.

2021-10-23 02:49 UTC, akhilveeraghanta requested changes
nice work! just a couple comments

2021-10-23 02:49 UTC, akhilveeraghanta commented on src/shared/parameter/config_definitions/passing_config.yaml
> +
seems like a random change made it in here

2021-10-23 02:49 UTC, akhilveeraghanta commented on src/software/ai/hl/stp/play/enemy_free_kick_play_test.cpp
> +        ::TestUtil::createGameState(RefereeCommand::NORMAL_START, RefereeCommand::DIRECT_FREE_THEM));
You could change this to be DIRECT_FREE_US to make sure we don't run this play on our free kick

2021-10-23 02:49 UTC, akhilveeraghanta commented on src/software/ai/hl/stp/play/enemy_free_kick_play_test.cpp
> +    //
Seems to be a stay comment here

2021-10-23 21:37 UTC, jameschuang2002 submitted a review, later dismissed
looks good to me

2021-10-27 05:01 UTC, jonathanlew reviewed
just a couple comments from me

2021-10-27 05:01 UTC, jonathanlew commented on src/software/ai/hl/stp/play/enemy_free_kick_play_test.cpp
> +                                                      RefereeCommand::DIRECT_FREE_THEM));
non-blocking: it'd be nice to test normal start as well

2021-10-27 05:01 UTC, jonathanlew commented on src/shared/parameter/config_definitions/passing_config.yaml
> +
I still see a new line here

2021-11-14 04:30 UTC, jonathanlew reviewed
LGTM except for the extra file

2021-11-14 04:30 UTC, jonathanlew commented on src/proto/define_a_proto_to_simulate_standalone_simulator_config
> +syntax = "proto3";
I think you forget to switch branches before working on your new ticket

2021-11-21 05:46 UTC, jonathanlew approved these changes
LGTM!

2021-11-21 15:10 UTC, akhilveeraghanta approved these changes

2021-11-26 04:02 UTC, merged