Renamed impl files to private and updated code style document
UBC-Thunderbots/Software pull request #2303
Opened 2021-10-22 22:06 UTC by HubertTheodore

## Please fill out the following before requesting review on this PR

### Description

    renamed _impl files to _private and updated code style guide document to reflect changes

### Testing Done

### Resolved Issues

resolves #1711 

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ x] **Remove all commented out code**
- [ x] **Remove extra print statements**: for example, those just used for testing
- [ x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-10-23 02:36 UTC, akhilveeraghanta requested changes
Something funky is going on with the Software submodule, try to delete the extra empty Software folder in the repo and make a new commit

You also need to update src/firmware/app/control/BUILD with the new file name

2021-10-23 20:06 UTC, LiCody requested changes
Looks good just need these changes to fix CI. Generally, you should run bazel build on your own machine before pushing a commit/opening a pr.

2021-10-23 20:06 UTC, LiCody commented on src/firmware/app/control/trajectory_planner_private.c
> +#include "firmware/app/control/trajectory_planner_impl.h"
```suggestion
#include "firmware/app/control/trajectory_planner_private.h"
```
Build is failing cause it cant find the _impl files should change these to use the renamed files

2021-10-23 20:06 UTC, LiCody commented on src/firmware/app/control/trajectory_planner_private_test.cpp
> +#include "firmware/app/control/trajectory_planner_impl.h"
```suggestion
#include "firmware/app/control/trajectory_planner_private.h"
```
same as above

2021-10-27 02:51 UTC, LiCody approved these changes
LGTM 👍

2021-10-27 04:59 UTC, jonathanlew approved these changes
LGTM!

2021-10-27 21:14 UTC, akhilveeraghanta approved these changes

2021-11-01 06:00 UTC, merged