Penalty friendly is applicale and invariant holds test
UBC-Thunderbots/Software pull request #2305
Opened 2021-10-23 20:09 UTC by divy-07

## Please fill out the following before requesting review on this PR

### Description

Implemented isApplicable and invariantHolds tests for PenaltyKickPlay. 
isApplicable() determines if the play should start running. invariantHolds() determines if the play should continue running. 

### Testing Done

Unit tests

### Resolved Issues

resolved #2254 

### Length Justification

---

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-10-23 20:38 UTC, PhilD71 submitted a review, later dismissed
LGTM!

2021-10-27 04:59 UTC, jonathanlew reviewed
just one non-blocking comment

2021-10-27 04:59 UTC, jonathanlew commented on src/software/ai/hl/stp/play/penalty_kick_play_test.cpp
> +        RefereeCommand::PREPARE_PENALTY_THEM, RefereeCommand::PREPARE_PENALTY_US));
I'd like to see a test with a more natural transition, such as PENALTY_US to NORMAL_START

2021-10-27 21:15 UTC, akhilveeraghanta requested changes
seems to be random empty file `...` that made it in

2021-10-31 01:03 UTC, divy-07 commented
sorry for a lot of commits, I had some issues with git and pushing

2021-11-01 00:23 UTC, jonathanlew commented on src/software/ai/hl/stp/play/penalty_kick_play_test.cpp
> +        RefereeCommand::NORMAL_START, RefereeCommand::PREPARE_PENALTY_US));
sorry this wasn't clear, but please also keep the PREPARE_PENALTY_THEM test

2021-11-06 22:09 UTC, divy-07 commented
> seems to be random empty file `...` that made it in
Fixed!

2021-11-07 04:07 UTC, jonathanlew reviewed
just a couple nits

2021-11-07 04:07 UTC, jonathanlew commented on src/software/ai/hl/stp/play/penalty_kick_play_test.cpp
> +                                                      RefereeCommand::NORMAL_START));
nit: this comment doesn't match the code

2021-11-07 04:07 UTC, jonathanlew commented on src/software/ai/hl/stp/play/penalty_kick_play_test.cpp
> +        RefereeCommand::PREPARE_PENALTY_US, RefereeCommand::PREPARE_PENALTY_US));
nit: this comment doesn't match the code

2021-11-09 02:21 UTC, jonathanlew approved these changes
LGTM!

2021-11-12 17:50 UTC, akhilveeraghanta approved these changes

2021-11-12 23:14 UTC, PhilD71 approved these changes
Good!

2021-11-13 01:39 UTC, merged