ai folder merge .tpp and .h to .hpp
UBC-Thunderbots/Software pull request #2327
Opened 2021-11-06 07:30 UTC by jameschuang2002

### Description

### Testing Done

### Resolved Issues

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**
Most items below are not relevant to this task.
- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-11-07 03:59 UTC, jonathanlew requested changes
just one comment from me

2021-11-07 03:59 UTC, jonathanlew commented on src/software/ai/passing/pass_evaluation.hpp
> +#include "software/ai/passing/pass.h"
please put this header at the top of the file

2021-11-07 05:11 UTC, akhilveeraghanta reviewed
lgtm pending Jons comment

2021-11-07 05:31 UTC, Bvasilchikov commented
lgtm to me as well

2021-11-07 07:12 UTC, jonathanlew approved these changes

2021-11-08 04:45 UTC, Bvasilchikov approved these changes
Looks good

2021-11-14 05:20 UTC, iammie9 approved these changes

2021-11-18 23:44 UTC, merged