James/ball robot translation from ersim
UBC-Thunderbots/Software pull request #2349
Opened 2021-11-20 20:10 UTC by jameschuang2002

## Please fill out the following before requesting review on this PR

### Description

### Testing Done

Basic Conversion of SimBall and SimRobot

### Resolved Issues

resolves #2328 
### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2021-11-21 06:02 UTC, jonathanlew requested changes
Looks good, just a few comments. Also please rename the title of this PR

2021-11-21 06:02 UTC, jonathanlew commented on src/proto/message_translation/er_force_world.h
> + *
missing param for timestamp

2021-11-21 06:02 UTC, jonathanlew commented on src/proto/message_translation/er_force_world.h
> + * @param sim_robot: the robot information retrieved from the er force simulator
missing param for timestamp

2021-11-21 06:02 UTC, jonathanlew commented on src/proto/message_translation/er_force_world.cpp
> +    double angle = 2 * Angle::acos(sim_robot.rotation().real()).toRadians();
Shouldn't this involve the non real parts of the quaternion as well? https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation

2021-11-26 06:36 UTC, jonathanlew commented on src/proto/message_translation/er_force_world.cpp
> +    const RobotState state(position, velocity, Angle::fromRadians(angle),
```suggestion
    Angle angle        = Angle::atan(siny_cosp / cosy_cosp);
    const RobotState state(position, velocity, angle,
```

2021-11-26 06:36 UTC, jonathanlew commented on src/proto/message_translation/er_force_world_test.cpp
> +    RobotState expected_state(expected_pos, expected_vel, Angle::fromRadians(0),
can we have a test where the expected angle is nonzero please?

2021-11-26 06:36 UTC, jonathanlew commented on src/proto/message_translation/er_force_world_test.cpp
> +                                               1e-6, Angle::fromDegrees(5)));
I think the degrees tolerance can be smaller like 1 degree or less

2021-11-29 21:18 UTC, jonathanlew approved these changes
LGTM assuming the quaternion conversion is correct

2021-12-03 01:51 UTC, akhilveeraghanta approved these changes
lgtm!

2021-12-04 19:16 UTC, merged