Configuring field size based on an argument for the ErForceSimulator constructor
UBC-Thunderbots/Software pull request #2375
Opened 2021-12-10 08:47 UTC by HubertTheodore

## Please fill out the following before requesting review on this PR

### Description

Made changes to the ErForceSimulator constructor so that it can take a field type argument.

### Testing Done

### Resolved Issues

resolves #2341 

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2022-01-09 06:52 UTC, jonathanlew requested changes
overall looks good, just missing a bit of testing

2022-01-09 06:52 UTC, jonathanlew commented on src/software/simulation/er_force_simulator.cpp
> +        full_filename = full_filename + CONFIG_FILE + "B.txt";
please add a comment to say we're loading the division B configuration here

2022-01-09 06:52 UTC, jonathanlew commented on src/software/simulation/er_force_simulator.cpp
> +#include "extlibs/er_force_sim/src/amun/simulator/simulator.h"
I don't think this is needed

2022-01-09 06:52 UTC, jonathanlew commented on src/software/world/field.h
> +    static Field createField(FieldType field_type);
please write a test for this function

2022-01-09 06:52 UTC, jonathanlew commented on src/software/simulation/er_force_simulator_test.cpp
> +                    }
please remove this debug code

2022-01-09 06:52 UTC, jonathanlew commented on src/software/simulation/er_force_simulator.cpp
> +    return field;
please add a test for this function, i.e. create an ErForceSimulator with DIV_A/DIV_B and check the Field returned by getField.

2022-01-13 05:39 UTC, jonathanlew requested changes
looks good, just a couple nits

2022-01-13 05:39 UTC, jonathanlew commented on src/software/simulation/er_force_simulator.h
> +    explicit ErForceSimulator(const FieldType& field_type,
please update the javadoc above

2022-01-13 05:39 UTC, jonathanlew commented on src/software/world/field.h
> +     * @return a field with the standard SSL Division A or B dimensions
please add an `@param` for this javadoc

2022-01-13 08:13 UTC, jonathanlew approved these changes
LGTM! :field_hockey:

2022-01-14 21:33 UTC, jameschuang2002 approved these changes

2022-01-15 03:26 UTC, merged