Gcc 9 supportv2
UBC-Thunderbots/Software pull request #2466
Opened 2022-02-09 18:18 UTC by jonathanlew

## Please fill out the following before requesting review on this PR

### Description

### Testing Done

### Resolved Issues

### Length Justification and Key Files to Review

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2022-02-11 04:28 UTC, itsarune reviewed
nice to have this in, one tiny thing

2022-02-11 04:28 UTC, itsarune commented on src/software/handheld_control_main.cpp
> +    // primitive_generator->Subject<TbotsProto::PrimitiveSet>::registerObserver(backend);
why commented out?

2022-02-11 04:50 UTC, jonathanlew commented on src/software/handheld_control_main.cpp
> +    // primitive_generator->Subject<TbotsProto::PrimitiveSet>::registerObserver(backend);
nice catch, fixed

2022-02-12 05:08 UTC, itsarune approved these changes, later dismissed

2022-02-13 05:36 UTC, akhilveeraghanta requested changes
`./thunderloop_main: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./thunderloop_main)`

doesn't seem to work out of the box on the jetson nano unfortunately :(

2022-02-15 17:06 UTC, akhilveeraghanta approved these changes

2022-02-16 07:53 UTC, itsarune approved these changes

2022-02-17 05:54 UTC, merged