Design protobufs to add, move, remove robots and move ball
UBC-Thunderbots/Software pull request #2484
Opened 2022-02-12 22:07 UTC by HubertTheodore

## Please fill out the following before requesting review on this PR

### Description

### Testing Done

### Resolved Issues

### Length Justification and Key Files to Review

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2022-02-18 05:28 UTC, akhilveeraghanta requested changes
looks great! just a couple of comments on MoveRobot

2022-02-18 05:28 UTC, akhilveeraghanta commented on src/proto/move_robot_and_ball_messages.proto
> +message MoveRobotMessage
you can remove the Message suffix, `MoveRobot` should be enough

2022-02-18 05:28 UTC, akhilveeraghanta commented on src/proto/move_robot_and_ball_messages.proto
> +{
we need a field here for robot id (to identify which robot to move)

2022-02-18 05:28 UTC, akhilveeraghanta commented on src/proto/move_robot_and_ball_messages.proto
> +    AngularVelocity global_angular_velocity = 4;
lets add another field here for Team color, looks like that's also needed to figured out which team to control

```
enum TeamColour                                                                                                                                                                                           
{                                                                                                                                                                                                                                                                                                                                                                          
    YELLOW = 1;                                                                                                                                                                                     
    BLUE = 2;                                                                                                                                                                                       
}   
```

And then add a field

`TeamColour team_colour = 5`;

2022-02-23 07:47 UTC, jonathanlew commented on src/proto/move_robot_and_ball_messages.proto
> +
this doesn't seem to be used anywhere?

2022-03-06 15:51 UTC, akhilveeraghanta approved these changes, later dismissed
lgtm!

2022-03-08 00:32 UTC, jonathanlew commented on src/proto/move_robot_and_ball_messages.proto
> +    RobotId robot_id                        = 6;
not sure why this can't be
```suggestion
    uint32 robot_id                        = 6;
```

2022-03-13 15:06 UTC, akhilveeraghanta approved these changes, later dismissed

2022-03-13 19:16 UTC, jonathanlew reviewed
one more comment here

2022-03-13 19:16 UTC, jonathanlew commented on src/proto/move_robot_and_ball_messages.proto
> +
bumping

2022-03-20 15:43 UTC, akhilveeraghanta approved these changes

2022-03-21 08:19 UTC, jonathanlew approved these changes

2022-03-22 06:54 UTC, merged