Thunderscope: Add RobotDiagnostics Drive and Dribbler Motor Control W…
UBC-Thunderbots/Software pull request #2527
Opened 2022-03-14 03:38 UTC by piramonpan

…idget

## Please fill out the following before requesting review on this PR

### Description

Add Drive, Dribble Motor Control Widgets into Thunderscope 

### Testing Done

### Resolved Issues
resolves #2463 

### Length Justification and Key Files to Review

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2022-03-15 15:03 UTC, akhilveeraghanta requested changes
great work! I really like how the widget looks in tscope :100:

2022-03-15 15:03 UTC, akhilveeraghanta commented on src/software/thunderscope/robot_diagnostics/drive_and_dribbler_widget.py
> +        tab2 = QWidget()
nit: you can rename these to `per_wheel_tab` and `direct_velocity_tab`

2022-03-15 15:03 UTC, akhilveeraghanta commented on src/software/thunderscope/robot_diagnostics/drive_and_dribbler_widget.py
> +        groupBox = QGroupBox(title)
nit: this should be `self.create_slider(self, title, min, max)` because it returns a slider

we also need to add docs here
checkout line 44 of `shared/parameter/proto_writer.py` for an example

2022-03-15 15:03 UTC, akhilveeraghanta commented on src/software/thunderscope/robot_diagnostics/drive_and_dribbler_widget.py
> +        backRight, slidebr = self.setSlider("Back Right")
lets change this to say so its a bit more  clear

`front_left_groupbox, front_left_slider = self.create_slider(..`)

2022-03-15 15:03 UTC, akhilveeraghanta commented on src/software/thunderscope/robot_diagnostics/drive_and_dribbler_widget.py
> +        stopAndreset.clicked.connect(lambda: slidebr.setValue(0))
you might want to make a function that does

~~~
def reset_all_sliders():
     front_left_slider.setValue(0)
     ...
     
~~~
which will allow you to register just 1 function here
we also want to call that function if the user switches tabs

2022-03-15 15:03 UTC, akhilveeraghanta commented on src/software/thunderscope/robot_diagnostics/drive_and_dribbler_widget.py
> +    def setUpDirectVelocity(self, title):
nit: missing docs here and below this, see example line 44 of `proto_writer.py`

2022-03-21 08:55 UTC, jonathanlew reviewed
nothing much to add

2022-03-21 08:55 UTC, jonathanlew commented on src/software/thunderscope/robot_diagnostics/drive_and_dribbler_widget.py
> +        stopAndreset = self.resetBtn()
nit: should be snake_case

2022-03-21 08:55 UTC, jonathanlew commented on src/software/thunderscope/robot_diagnostics/drive_and_dribbler_widget.py
> +        slider.valueChanged.connect(label.setNum)
is the idea to poll this slider to set motor speeds or to use callbacks?

2022-04-04 04:28 UTC, akhilveeraghanta reviewed
almost there! ran it locally and ran into these two typos/bugs

2022-04-04 04:28 UTC, akhilveeraghanta commented on src/software/thunderscope/robot_diagnostics/drive_and_dribbler_widget.py
> +        direct_velocity_tab.setLayout(direct_velocity_tab.grid2)
i think the `setUpDirectVelocity` needs to be renamed to `setup_up_direct_velocity`

2022-04-04 04:28 UTC, akhilveeraghanta commented on src/software/thunderscope/robot_diagnostics/drive_and_dribbler_widget.py
> +        layout.addWidget(self.setUpDribbler("  Dribbler"))
this function needs to be renamed

2022-04-04 23:50 UTC, akhilveeraghanta submitted a review, later dismissed

2022-04-05 00:49 UTC, jonathanlew approved these changes, later dismissed
couple non blocking comments

2022-04-05 00:49 UTC, jonathanlew commented on src/software/thunderscope/robot_diagnostics/drive_and_dribbler_widget.py
> +            "Front Left", -100, 100, 1
-100 100 should be pulled out into constants

2022-04-05 00:49 UTC, jonathanlew commented on src/software/thunderscope/robot_diagnostics/drive_and_dribbler_widget.py
> +        xms, self.slidexms = self.create_slider("X (m/s)", -1000, 1000, 10)
-1000 1000 should be pulled out into constants

2022-04-05 01:44 UTC, akhilveeraghanta submitted a review, later dismissed

2022-04-05 02:57 UTC, akhilveeraghanta approved these changes

2022-04-05 03:00 UTC, jonathanlew approved these changes

2022-04-05 03:58 UTC, merged