i think it works
UBC-Thunderbots/Software pull request #2626
Opened 2022-05-21 05:27 UTC by divy-07

## Please fill out the following before requesting review on this PR

### Description

Changes in Play info widget in thunderscope. Now the row size changes based on the number of robots on the field.

### Testing Done

ran thunderscope

### Resolved Issues

resolves #2560 

### Length Justification and Key Files to Review

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2022-05-21 16:12 UTC, akhilveeraghanta approved these changes, later dismissed
clean solution!

2022-05-22 20:19 UTC, jonathanlew requested changes
please address the todo at line 16 in src/software/thunderscope/play/playinfo_widget.py

2022-05-23 18:51 UTC, akhilveeraghanta approved these changes

2022-05-23 21:53 UTC, jonathanlew approved these changes

2022-05-24 15:57 UTC, merged