finding best chip region for pivot kick
UBC-Thunderbots/Software pull request #2698
Opened 2022-07-12 08:02 UTC by xyztiger

## Please fill out the following before requesting review on this PR

### Description

### Testing Done

### Resolved Issues

### Length Justification and Key Files to Review

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2022-07-12 14:44 UTC, jordanzliu requested changes

2022-07-12 14:44 UTC, jordanzliu commented on src/software/ai/evaluation/find_open_areas.h
>   * @return a vector of circles where the center is a good point to chip to, and the
u forgot to fix the javadoc comment

2022-07-12 14:44 UTC, jordanzliu commented on src/software/ai/hl/stp/tactic/goalie/goalie_fsm.cpp
> +    Point clear_corner_1 = Point(goalie_pos.x() + MAX_CHIP_DISTANCE - 1, 1.8);
magic numbers should be named constants

2022-07-13 02:39 UTC, itsarune reviewed
looks good when I tested it locally, can you add some validation for it

2022-07-13 02:39 UTC, itsarune commented on src/software/ai/evaluation/find_open_areas.cpp
>      double posFieldY = world.field().enemyCornerPos().y() - inset;
this isn't related to your changes but by convention, we use ball_x, field_x, neg_field_y and pos_field_y

2022-07-13 02:39 UTC, itsarune commented on src/software/ai/evaluation/find_open_areas.cpp
> +std::vector<Circle> findGoodChipTargets(const World& world,
could you add some validation for this?

2022-07-13 07:38 UTC, xyztiger commented on src/software/ai/evaluation/find_open_areas.cpp
> +std::vector<Circle> findGoodChipTargets(const World& world,
added unit tests

2022-09-29 19:16 UTC, closed without merging