Changed the hardcoded redis-keys to CPP constants
UBC-Thunderbots/Software pull request #2744
Opened 2022-10-08 21:39 UTC by rachad47

## Please fill out the following before requesting review on this PR

### Description@@ -32,11 +33,11 @@ class ScreenActions:

   Went to existing ,py files that were using the constants from the py_constants.cpp and checked the way they imported the C++ file into python so I can the same under the .py file I edited.

Resolves #2728

### Length Justification and Key Files to Review

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2022-10-11 03:44 UTC, LiCody requested changes
Also some occurrences in /software/jetson_nano/display/screens/home_screen.py

2022-10-11 03:44 UTC, LiCody commented on src/software/constants.h
> +const std::string CAPACITOR_VOLTAGE_REDIS_KEY       = "/cap_voltage";
```suggestion
const std::string ROBOT_CAPACITOR_VOLTAGE_REDIS_KEY = "/cap_voltage";
```
Can we change this to match the other variable names in the file

2022-10-11 20:05 UTC, nimazareian requested changes
Overall looks good to me, just had 1 nit and noticed that a few variables still need to be updated.

2022-10-11 20:05 UTC, nimazareian commented on src/software/jetson_nano/display/robot_ui.py
>  # TODO(#2728): Replace key strings with values from constants
Now that you're resolving a ticket, don't forget to remove it's TODOs in the code as well.
You can search globally in CLion (`ctrl + shift + f`) or use `ag` in the terminal from the `src` folder to search the ticket number (i.e. `ag 2728`), and find the locations of the two other TODO comments for this ticket as well.

2022-10-11 20:05 UTC, nimazareian commented on src/software/jetson_nano/display/robot_ui.py
>  # TODO(#2728): Replace key strings with values from constants
The two other TODOs will also show you some of the other places where the hard coded string keys can be replaced with these constants. One of them is in `home_screen.py`. The other TODO in `network.cpp` I think is actually labelled incorrectly and should be tagging #2727 instead. I would appreciate it if you could update that as well!

2022-10-22 18:36 UTC, LiCody approved these changes

2022-10-24 20:30 UTC, nimazareian approved these changes
LGTM! 💯

2022-10-25 03:27 UTC, merged