updating all hrvo instances in the codebase
UBC-Thunderbots/Software pull request #2806
Opened 2023-01-14 20:00 UTC by sarphion

## Please fill out the following before requesting review on this PR

### Description

### Testing Done

### Resolved Issues

### Length Justification and Key Files to Review

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2023-01-17 05:16 UTC, raymond212 requested changes
Thanks for renaming the many HRVO instances in the codebase! I think the changes look pretty good overall. However, I believe instances of `HRVO` in comments can be left in all caps. Also, it would be helpful to link the related issue in the PR description. 

I've also noticed that it's been a few days, but the github checks haven't completed yet... Maybe try re-running the checks?

2023-01-17 05:16 UTC, raymond212 commented on src/extlibs/hrvo/agent.h
> + * An agent/robot in the Hrvo simulation.
I think acronyms can be left in all-caps in the comments? This also applies to other changes to comments. 
```suggestion
 * An agent/robot in the HRVO simulation.
```

2023-01-18 18:43 UTC, williamckha reviewed
LGTM! Just a small nit

2023-01-18 18:43 UTC, williamckha commented on src/software/constants.h
> +const std::string BLUE_Hrvo_PATH                         = "/blue_hrvo";
I believe we should keep these constants in all caps

2023-01-18 20:09 UTC, AdenC123 reviewed
Same as @williamckha - believe constants should be in all caps. Otherwise looks great

2023-01-18 20:09 UTC, AdenC123 commented on src/extlibs/hrvo/kd_tree.cpp
> +    if (end - begin > Hrvo_MAX_LEAF_SIZE)
constants should probably be left in all caps?

2023-01-18 20:09 UTC, AdenC123 commented on src/extlibs/hrvo/simulator.cpp
> +        LOG(VISUALIZE, YELLOW_Hrvo_PATH) << hrvo_visualization;
these constants as well

2023-02-03 22:47 UTC, itsarune reviewed
great start!

two notes:
- in comments, we should be using the human-readable acronym HRVO
- you have merge conflict markers, "<<<<<" and "HEAD" messages. this stops our code from compiling and we need to resolve them. you should be able to resolve them in your IDE or we can take a look at it together on Saturday

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/simulated_hrvo_test.cpp
> +>>>>>>> c070809816e7711d3e1d65d4a1aef0a54d866bb7
merge conflict market, you can delete this line

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/simulated_hrvo_test.cpp
> +<<<<<<< HEAD
git conflict marker, you may delete this line

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/simulated_hrvo_test.cpp
> +=======
git conflict market,  you may delete this line

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/hrvo_agent.cpp
> + * Hrvo Library
this can be HRVO (in comments)

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/hrvo_agent.cpp
> +    // be running Hrvo
can be HRVO here

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/hrvo_agent.h
> + * Hrvo Library
can be HRVO

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/hrvo_agent.h
> + * An agent/robot in the simulation which uses the Hrvo algorithm to motion plan towards
comments can be HRVO

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/kd_tree.cpp
> + * Hrvo Library
comments, can be HRVO

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/kd_tree.h
> + * Hrvo Library
comments, can be HRVO

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/simulator.cpp
> + * Hrvo Library
comments: can be HRVO

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/simulator.h
> + * Hrvo Library
comments: can be HRVO

2023-02-03 22:47 UTC, itsarune commented on src/software/jetson_nano/primitive_executor.cpp
> +=======
conflict marker, you can delete this line

2023-02-03 22:47 UTC, itsarune commented on src/software/jetson_nano/primitive_executor.cpp
> +>>>>>>> c070809816e7711d3e1d65d4a1aef0a54d866bb7
conflict marker, delete this line

2023-02-03 22:47 UTC, itsarune commented on src/software/jetson_nano/primitive_executor.h
>      HRVOSimulator hrvo_simulator_;
conflict marker: delete these lines

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/simulator.h
> +     * Get friendly Hrvo agent from robot id. Returns std::nullopt if agent does not exist
in comments, we can use HRVO

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/simulator.h
> +     * @return Optional shared pointer to an Hrvo agent
in comments, we can use "HRVO"

2023-02-03 22:47 UTC, itsarune commented on src/extlibs/hrvo/simulator.cpp
> +        // Hrvo friendly agent with robot id can not be visualized
comments: "HRVO"

2023-02-23 19:15 UTC, raymond212 reviewed
Looks pretty good, I just had two suggestions.

2023-02-23 19:15 UTC, raymond212 commented on src/extlibs/hrvo/simulator.h
> +    // The maximum distance which Hrvo Agents will look for neighbors, in meters.
Can be HRVO

2023-02-23 19:15 UTC, raymond212 commented on src/extlibs/hrvo/simulator.cpp
> +                 << " can not be found since it does not exist in Hrvo Simulator"
HRVO is probably okay for log messages.

2023-03-02 11:20 UTC, itsarune reviewed
two small things

2023-03-02 11:20 UTC, itsarune commented on src/extlibs/hrvo/hrvo_agent.cpp
> +    // Convert velocity obstacle to hybrid reciprocal velocity obstacle (Hrvo)
```suggestion
    // Convert velocity obstacle to hybrid reciprocal velocity obstacle (HRVO)
```

2023-03-02 11:20 UTC, itsarune commented on src/extlibs/hrvo/simulator.cpp
> +        // Hrvo friendly agent with robot id can not be visualized
bump

2023-03-18 05:43 UTC, nimazareian commented
Closing in favour of a full HRVO rewrite in #2814

2023-03-18 05:43 UTC, closed without merging