Shortcut for pausing/resuming simulation in thunderscope
UBC-Thunderbots/Software pull request #2827
Opened 2023-02-11 20:40 UTC by sarphion

## Please fill out the following before requesting review on this PR

### Description
You can click on the field widget, then press ctrl + space to toggle between pause and unpause state of the simulation.

### Testing Done

### Resolved Issues
Related to #2842 

### Length Justification and Key Files to Review

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2023-02-12 08:43 UTC, nimazareian requested changes
Overall looks good to me! Just some nits regarding the comments

2023-02-12 08:43 UTC, nimazareian commented on src/proto/world.proto
> +    // for the future, if adding a speed functionality, the proto should be added here
This comment can be removed.

2023-02-12 08:43 UTC, nimazareian commented on src/software/thunderscope/field/world_layer.py
> +        # if user is holding ctrl + space, send a command to simulator to pause the gameplay
nit:
```suggestion
        # if user is holding ctrl + space, send a command to simulator to pause/play the gameplay
```

2023-02-12 08:43 UTC, nimazareian commented on src/software/thunderscope/field/world_layer.py
> +            """
This comment can be removed. Seems to be copied from another class

2023-02-12 08:43 UTC, nimazareian commented on src/software/thunderscope/thunderscope_main.py
> +            # or would it be tscope.simulator_proto_unix_io.register_observer(SimulationState, self.simulation_state_buffer)
Likewise, these comments

2023-02-15 01:13 UTC, itsarune reviewed
looks good, pending nima's comments

2023-02-19 09:06 UTC, sarphion reviewed
removed unnecessary comments

2023-02-21 02:07 UTC, sauravbanna approved these changes
looks good to me!

2023-02-21 06:31 UTC, nimazareian approved these changes
LGTM!

2023-02-23 16:44 UTC, merged