Thunderscope: play/pause simulation button and shortcut
UBC-Thunderbots/Software pull request #2865
Opened 2023-03-18 20:13 UTC by sarphion

## Please fill out the following before requesting review on this PR

### Description
 A new toolbar added, which has a pause/play button. if pressed, the simulation will pause, and if it is in the pause state, and the button is pressed, the simulation resumes back to playing. 
    when button pressed, or the shortcut is used (ctrl+space), the button changes icon as well.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2023-03-20 03:33 UTC, williamckha reviewed
This is cool! Nice to see these features being added to thunderscope, will be helpful for a project I'm working on

2023-03-20 03:33 UTC, williamckha commented on src/software/thunderscope/thunderscope.py
> +        pixmapi_pause = QStyle.StandardPixmap.SP_MediaStop
Would a pause icon be better suited here? `SP_MediaPause`
A stop icon might be confused for halting/exiting the simulation

2023-03-25 19:33 UTC, itsarune approved these changes
[ignore]

2023-03-25 19:33 UTC, itsarune requested changes
nice work getting it to work!

I'd like the toolbar to be right under the field widget: 
![image](https://user-images.githubusercontent.com/42703774/227737698-21ba8a37-0985-47ce-b885-03f530fd6983.png)

right now, you have to hunt down the toolbar. Also, I'd like the toolbar to be centred on its panel as well

2023-04-01 19:22 UTC, sarphion commented on src/software/thunderscope/thunderscope.py
> +        pixmapi_pause = QStyle.StandardPixmap.SP_MediaStop
I agree! Thanks! I changed it to a pause icon in my most recent commit

2023-04-01 19:57 UTC, williamckha submitted a review, later dismissed

2023-04-08 06:03 UTC, nimazareian commented on src/software/thunderscope/field/world_layer.py
> +from software.thunderscope.constants import LINE_WIDTH
Some of these changes seem to be made by accident when fixing merge conflicts and are unrelated to this ticket. They should be reverted to how they are on master.

2023-04-08 06:03 UTC, nimazareian commented on src/software/thunderscope/field/world_layer.py
> -        painter.drawEllipse(self.createCircle(ball_state.global_position, ball_radius))
Likewise here with unwanted changes

2023-04-08 06:03 UTC, nimazareian commented on src/software/thunderscope/thunderscope.py
> +    from PyQt6.QtWebEngineWidgets import QWebEngineView
Much of the changes in this file as well

2023-04-08 06:03 UTC, nimazareian commented on src/software/thunderscope/thunderscope_main.py
> +            )
This seems to be a duplicate of the code write above it

2023-04-11 00:42 UTC, itsarune reviewed
looks like after fixing the merge conflicts, you also have some dependency errors when you run thunderscope_main, so I'd recommend reverting the merge and re-doing it

2023-09-30 20:48 UTC, itsarune commented
will re-open later, stale PR

2023-09-30 20:49 UTC, closed without merging