Hrvo path optionals
UBC-Thunderbots/Software pull request #2888
Opened 2023-04-02 19:23 UTC by Bvasilchikov

## Please fill out the following before requesting review on this PR

### Description

### Testing Done

### Resolved Issues

### Length Justification and Key Files to Review

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2023-04-03 06:54 UTC, nimazareian approved these changes

2023-04-04 19:40 UTC, nimazareian requested changes
There seems to be another risky optional access here:
https://github.com/UBC-Thunderbots/Software/blob/c3d763daef63e718727478222a84c5ae9f54617b/src/software/ai/navigator/path_planner/hrvo/hrvo_agent.cpp#L79-L82

We should probably return and empty list of neighbors if there's no path point (we're at our destination)

2023-04-07 02:29 UTC, nimazareian approved these changes, later dismissed

2023-04-07 04:01 UTC, nimazareian approved these changes

2023-04-07 09:13 UTC, itsarune approved these changes

2023-04-07 18:32 UTC, merged