protobuf function name update
UBC-Thunderbots/Software pull request #3014
Opened 2023-10-07 19:22 UTC by Isabella373

## Please fill out the following before requesting review on this PR

### Description

### Testing Done

### Resolved Issues

### Length Justification and Key Files to Review

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2023-10-13 02:23 UTC, nimazareian requested changes
The goal of #2901 is to rename our own helper functions for creating proto (i.e. protobuf) objects. These functions can be found in [`src/proto/message_translation/tbots_protobuf.h`](https://github.com/UBC-Thunderbots/Software/blob/master/src/proto/message_translation/tbots_protobuf.h). The functions under `src/extlibs` shouldn't need to change, since the code there are from the external libraries we use (i.e. it is not actually the code we write).

To do this ticket, I suggest going to `tbots_protobuf.h` in CLion, and using [CLion's refactoring tools](https://www.jetbrains.com/help/clion/rename-refactorings.html) to rename the functions (right-click on the function name > refactor > rename). This is nice, since CLion is generally very good at finding everywhere the function is used, and updating all those references as well. 

In my opinion, a good name for the functions for be to just add the word `Proto` after the type. E.g. `createWorld` -> `createWorldProto`, `createRobot` -> `createRobotProto` ...

Also, could you update the description of your PR? We've included some comments in the description template that should guide you to filling it out (e.g. adding "resolves #<ticket number>" so the ticket automatically closes once you finish your PR)

2023-10-13 03:44 UTC, jameschuang2002 requested changes
Overall it looks good. 

However, there is a compilation error *createProtobufPassVisualization(passes) and I think that is why the gameplay and software tests are not passing. 

After fixing this I think this is good to go.

2023-10-23 00:54 UTC, itsarune reviewed
nothing more from me, pending fixing Nima's and James's comments

2023-12-01 05:08 UTC, nimazareian commented
Closing in favour of #3059

2023-12-01 05:08 UTC, closed without merging