Isabella branch for Protobuf
UBC-Thunderbots/Software pull request #3059
Opened 2023-11-24 14:17 UTC by Isabella373

## Please fill out the following before requesting review on this PR

### Description

### Testing Done

### Resolved Issues

### Length Justification and Key Files to Review

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2023-12-01 05:52 UTC, nimazareian reviewed
LGTM! :100: Just pending the merge conflict and the failing CI (should get fixed once you pull from master branch)

2023-12-02 19:46 UTC, itsarune commented on src/software/sensor_fusion/sensor_fusion.h
> +        const std::vector<BallDetection> &ball_detections);
`Ball` [isn't a proto type,](https://github.com/UBC-Thunderbots/Software/blob/master/src/software/world/ball.h) this should remain as `createBall`

2023-12-02 19:48 UTC, itsarune commented on src/software/test_util/test_util.cpp
> +    GameState createGameStateProto(const RefereeCommand &current_referee_command,
GameState is a c++ type, not a Proto type (a proto is any file found in software/proto), this should remain as the same

[GameState](https://github.com/UBC-Thunderbots/Software/blob/master/src/software/world/game_state.h)

2023-12-02 19:48 UTC, itsarune commented on src/software/test_util/test_util.h
> +    GameState createGameStateProto(const RefereeCommand &current_referee_command,
GameState is a c++ type, not a Proto type (a proto is any file found in software/proto), this should remain as the same

[GameState](https://github.com/UBC-Thunderbots/Software/blob/master/src/software/world/game_state.h)

2023-12-02 19:49 UTC, itsarune commented on src/software/world/field.cpp
> +Field Field::createFieldProto(TbotsProto::FieldType field_type)
this is returning a C++ Field object (not a proto that is generated by the protobuf compiler).

2023-12-02 19:50 UTC, itsarune commented on src/software/world/field.h
> +    static Field createFieldProto(TbotsProto::FieldType field_type);
this is returning a C++ type, not a Proto type

2023-12-02 19:55 UTC, itsarune requested changes
Good start!

I think there is a bit of a confusion here. We want to rename functions that create a Protobuf type. A Protobuf type is automatically generated by the C++ protobuf compiler and in our codebase, we store them here: https://github.com/UBC-Thunderbots/Software/tree/master/src/proto

In our code, these Proto types are seen as "TbotsProto::PassVisualization", "TbotsProto::BallState", etc. We want to rename functions that return these proto-based types.

It is confusing that sometimes we mimic these proto names to create equivalent c++ classes (BallState [ball_state.h], Ball [ball.h], GameState [game_state.h] etc.). These are c++ objects and these shouldn't be renamed.

So if a function returns: TbotsProto::GameState -> rename the function to `createGameStateProto`.
Likewise, if a function returns GameState -> this function should be called `createGameState`

2023-12-02 20:10 UTC, jameschuang2002 reviewed
I have the same comment as Arun. I think we should follow the old convention with protobuf naming

2024-01-27 19:48 UTC, closed without merging