Polygon support for visualizer messenger
UBC-Thunderbots/Software pull request #313
Opened 2019-02-02 21:28 UTC by FSXAC

### Description

Added ability to use VisualizerMessenger to send polygon shape messages

### Testing Done

Compiled; low risk

### Resolved Issues

Resolves #258 

### Length Justification

N/A

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2019-02-02 23:28 UTC, garethellis0 requested changes
This is looking good, just two small comments.

2019-02-04 18:05 UTC, FSXAC commented on src/thunderbots/software/util/visualizer_messenger/visualizer_messenger.h
> +                      std::vector<std::pair<double, double>>& vertices,
Right, will fix that today

2019-02-04 18:05 UTC, FSXAC commented on src/thunderbots/software/util/visualizer_messenger/visualizer_messenger.h
> +         * Reuqest a message to draw a polygon shape. The origin is the
Oops, nice catch

2019-02-05 05:49 UTC, FSXAC commented on src/thunderbots/software/util/visualizer_messenger/visualizer_messenger.h
> +                      std::vector<std::pair<double, double>>& vertices,
Updated

2019-02-05 08:07 UTC, garethellis0 approved these changes
LGTM :+1: :tada:

2019-02-05 17:46 UTC, merged