Tscope errors
UBC-Thunderbots/Software pull request #3133
Opened 2024-02-03 22:52 UTC by Bvasilchikov

## Please fill out the following before requesting review on this PR

### Description

Have you ever noticed how tscope scares you with long errors after you shutdown? Well fear no more! 

This PR fixes some missing type handling for handling network listeners, and adds some missing imports.

### Testing Done

- [x] Tried clicking "Info" button in robot view - no error in console
- [x] On diagnostics only shutdown, no more complaints about closing a non-existent tcp listener's. 

### Resolved Issues

Less errors is always better!

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2024-02-03 23:22 UTC, nimazareian approved these changes

2024-02-04 06:37 UTC, williamckha approved these changes, later dismissed

2024-02-04 06:37 UTC, williamckha commented on src/software/thunderscope/robot_communication.py
> +            self.receive_ssl_referee_proto.close()
any reason why we use two if blocks instead of one?

2024-02-04 16:10 UTC, nimazareian requested changes

2024-02-04 16:10 UTC, nimazareian commented on src/software/thunderscope/robot_communication.py
> +            self.receive_ssl_referee_proto.close()
oh William is right, I misread this line
```suggestion
        if self.receive_ssl_referee_proto:
            self.receive_ssl_referee_proto.close()
```

2024-02-10 15:36 UTC, itsarune reviewed
nothing much to add beyond what nima & william pointed out

2024-02-11 00:29 UTC, williamckha approved these changes

2024-02-11 02:37 UTC, nimazareian approved these changes

2024-02-11 02:41 UTC, merged