James/malfunction detection functions
UBC-Thunderbots/Software pull request #3168
Opened 2024-03-23 20:12 UTC by jameschuang2002

## Please fill out the following before requesting review on this PR

### Description

This PR includes a malfunction detection function that can detect injured robots with error codes, motor over temperature warnings, and break beam malfunction through comparison status messages with the ball.

### Testing Done

Basic unit tests were written for each form of detection.

### Resolved Issues

resolves #3090 

### Length Justification and Key Files to Review

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

2024-03-30 18:39 UTC, sauravbanna requested changes
looks great! tests are thorough, just some minor doc issues

2024-03-30 18:39 UTC, sauravbanna commented on src/software/ai/hl/stp/play/play.cpp
> +            primitives_to_run->mutable_robot_primitives()->insert(
nit: a small comment here explaining what these lines are doing could be helpful

2024-03-30 18:39 UTC, sauravbanna commented on src/software/ai/hl/stp/play/play.cpp
> +    return injured_robots;
shouldn't we be getting the injured robots from the world object?

2024-03-30 18:39 UTC, sauravbanna commented on src/software/ai/hl/stp/play/tactic_assignment.cpp
> +    //        -1,-1, 0,
explanations are great, makes it a lot easier to understand!

2024-03-30 18:39 UTC, sauravbanna commented on src/software/ai/hl/stp/play/tactic_assignment.h
> + * Assigns the given tactics to as many of the given robots
nit: i think we can mention the hungarian algorithm / a bit more about how the assignment is done here

2024-03-30 18:39 UTC, sauravbanna commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +    auto robot_navigation_obstacle_config = ai_config.robot_navigation_obstacle_config();
nit: maybe i'm misreading this but this test only has robot_0 right? where did robot_1 come from?

edit: comment seems to be from a later test

2024-03-30 18:39 UTC, sauravbanna commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +    EXPECT_FALSE(asst.find(move_tactic_1) != asst.end());
the comment mentions move_tactic_1 should be assigned, but it seems like this assertion checks the opposite?

also nit: do we wanna check for ID as well in these assertions?

2024-03-30 18:39 UTC, sauravbanna commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +// TEST_F(TacticAssignmentTest,
do we wanna keep the below test?

2024-03-30 18:39 UTC, sauravbanna commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +    }
do we want to add an assertion as well that the other robots have StopTactic assigned to them? looks like we're only checking that the intended robot has MoveTactic assigned

2024-03-30 18:39 UTC, sauravbanna commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +// TEST_F(TacticAssignmentTest, test_assignment_with_tiered_assignment)
do we want to keep this test?

2024-03-30 18:39 UTC, sauravbanna commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +TEST_F(TacticAssignmentTest, test_offense_play_with_substitution)
nit: would this be better suited in offense_play_test.py or some other offense play specific test file?

2024-04-01 09:03 UTC, itsarune commented on src/software/ai/hl/stp/play/tactic_assignment.h
> + * @param robots_to_assign The robots to assign to
missing doc params `obstacle_factory`, `obstacle_list`, `path_visualization`

2024-04-04 02:39 UTC, itsarune commented on src/software/ai/hl/stp/play/play.h
> +    virtual std::vector<Robot> getInjuredRobots(const World& world);
missing docs

2024-04-04 15:57 UTC, itsarune commented on src/software/sensor_fusion/sensor_fusion.cpp
> +                if (dist_vector->length() > 2)
make `2` a static const

2024-04-04 16:03 UTC, itsarune commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +        // Give an explicit seed to STP so that our tests are deterministic
you can delete this line (line 29)

2024-04-04 16:13 UTC, itsarune commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +TEST_F(TacticAssignmentTest, test_offense_play_with_substitution)
good point

2024-04-04 16:16 UTC, itsarune reviewed
looking good... @sauravbanna had some good questions that you should address (in this PR or the other ones)

2024-04-06 16:22 UTC, jameschuang2002 commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +    auto robot_navigation_obstacle_config = ai_config.robot_navigation_obstacle_config();
this one was addressed in #3031

2024-04-06 16:24 UTC, jameschuang2002 commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +// TEST_F(TacticAssignmentTest, test_assignment_with_tiered_assignment)
This was addressed in #3031. I added a new issue and tagged it, it's not really the focus on either PRs so would rather not to deal with it now

2024-04-06 16:26 UTC, jameschuang2002 commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +TEST_F(TacticAssignmentTest, test_offense_play_with_substitution)
We have discussed this possibility while implementing; however, offense_play_test does not offer the flexibility to do tactic assignment manually and do the necessary lower-level validations. I would be happy to change it if there's a way to do it, my initial thought is also to put it in offense_play_test

2024-04-06 16:27 UTC, jameschuang2002 commented on src/software/ai/hl/stp/play/tactic_assignment_test.cpp
> +// TEST_F(TacticAssignmentTest,
This was addressed in https://github.com/UBC-Thunderbots/Software/issues/3031. I added a new issue and tagged it, it's not really the focus on either PRs so would rather not to deal with it now

2024-04-06 16:31 UTC, jameschuang2002 commented on src/software/ai/hl/stp/play/play.cpp
> +    return injured_robots;
thanks for catching this, I don't think I ever use this one, I deleted it. The major function I was using is in team.cpp.

2024-04-06 16:51 UTC, jameschuang2002 commented
I think a lot of the comments on tactic_assignment_test.cpp is good; however, since I only ported those from the old stp_test.cpp, I am unsure about what the majority of those are doing. I would be happy to address those but is better to tag it as an issue because the malfunction detection should be the major feature?

2024-04-26 07:44 UTC, itsarune commented on src/software/sensor_fusion/sensor_fusion.h
> +     * @return the list of robotids of the injured robots
this @return does not match the function definition

2024-04-26 07:44 UTC, itsarune commented on src/software/sensor_fusion/sensor_fusion.h
> +    const static int break_beam_tolerance = 2;
constants should be CAPITAL_CASE

2024-04-26 07:44 UTC, itsarune reviewed
left a few comments

2024-09-20 02:57 UTC, closed without merging