Improve Ball timestamping and prediction
UBC-Thunderbots/Software pull request #54
Opened 2018-09-19 06:56 UTC by MathewMacDougall

Update the Ball class to use `std::chrono` for timestamps. Also added a new `updateState` function to update the Ball's state to a predicted future state. Useful for when the AI node runs several times without getting updates from vision, but we want to act with the most up-to-date/accurate information.

If anyone has naming suggestions to make the different `update` functions more clear I'm all ears.

I'm going to roll out a few timestamp changes before finishing the last `Team` and `World` implementations. This is the first part.

partially resolved #49

2018-09-19 15:10 UTC, garethellis0 requested changes
Looks pretty good, I like the design decisions made with respect to timestamps here.

2018-09-19 15:57 UTC, MathewMacDougall commented on src/thunderbots/software/ai/world/ball.h
> +    void updateState(std::chrono::time_point<std::chrono::steady_clock> timestamp);
Yes makes sense. I like that wording better

2018-09-19 16:00 UTC, MathewMacDougall commented on src/thunderbots/software/test/world/ball.cpp
> +    auto current_time = steady_clock::now();
Looks like you sort of can by creating time points relative to the epoch.
https://stackoverflow.com/questions/24913749/c11-chrono-create-time-point-from-number
https://stackoverflow.com/questions/30756919/convert-chrono-duration-to-time-point

Think it's worth?

2018-09-19 18:16 UTC, garethellis0 commented on src/thunderbots/software/test/world/ball.cpp
> +    auto current_time = steady_clock::now();
Yeah, you can set up a time once, like:
```
class BallTest : public ::testing::Test {
 protected:
    // You can define per-test set-up logic as usual.
  virtual void SetUp() { ... }

  // You can define per-test tear-down logic as usual.
  virtual void TearDown() { ... }

  // Some expensive resource shared by all tests. (TIME WOULD GO HERE)
  static T* shared_resource_;
};
```
and then making the tests look like:
```
TEST_F(BallTest, construct_with_params){
    shared_resource_.blahBlah()
    ....
}
```

2018-09-20 14:51 UTC, garethellis0 approved these changes
LGTM :+1: :tada:

2018-09-20 14:51 UTC, merged