Added calcBestShotOnFriendlyGoal functions and tests
UBC-Thunderbots/Software pull request #555
Opened 2019-04-20 04:40 UTC by MathewMacDougall

## Please fill out the following before requesting review on this PR

### Description

Added `calcBestShotOnFriendlyGoal` evaluation functions and restructured the `calcBestShot` functions a bit to more easily support both teams. Also removed the `calcBestShotAll` versions because YAGNI.

### Testing Done

Unit tests added

### Resolved Issues

None

### Length Justification

A fair amount of stuff was changed or moved so it adds up to just over 500 lines

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2019-04-20 10:59 UTC, garethellis0 requested changes
Looking pretty good to me, no major comments. I should be able to make this fit in with my changes fairly neatly.

2019-04-20 10:59 UTC, garethellis0 commented on src/thunderbots/software/ai/hl/stp/evaluation/calc_best_shot.h
> +     * @param goal_post_posThe goal post of the net with the positive y-coordinate
``` suggestion
     * @param goal_post_pos The goal post of the net with the positive y-coordinate
```

2019-04-20 10:59 UTC, garethellis0 commented on src/thunderbots/software/ai/hl/stp/evaluation/calc_best_shot.h
> +                                               bool shoot_at_enemy_goal);
I'm a bit confused, the `shoot_at_enemy_goal` doesn't appear anywhere else in this PR? Regardless, this seems a kinda icky way to do this, I think just have the two separate functions is probably a better call.

2019-04-23 02:05 UTC, EvanMorcom reviewed
Looks pretty good to me.

2019-04-23 02:10 UTC, MathewMacDougall commented on src/thunderbots/software/ai/hl/stp/evaluation/calc_best_shot.cpp
> +            // If not shot is found, at least set the target to the goal
fixed

2019-04-23 02:10 UTC, MathewMacDougall commented on src/thunderbots/software/ai/hl/stp/evaluation/calc_best_shot.h
> +     * @param goal_post_posThe goal post of the net with the positive y-coordinate
fixed

2019-04-23 02:14 UTC, garethellis0 approved these changes
LGTM :+1: :tada:

2019-04-23 02:46 UTC, merged