Misc fixes and features
UBC-Thunderbots/Software pull request #657
Opened 2019-06-26 06:22 UTC by MathewMacDougall

## Please fill out the following before requesting review on this PR

### Description

* Added the ability to set friendly and enemy goalies
* Fixed bug where setting "run_ai" to false would stop drawing in the visualizer
* Added the ability to select team colour

### Testing Done

Local testing

### Resolved Issues

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2019-06-26 14:58 UTC, garethellis0 requested changes
Just one comment, looks good otherwise!

2019-06-26 14:58 UTC, garethellis0 commented on src/thunderbots/software/util/parameter/config/ai_control.yaml
> +#        Overrides the friendly goalie id provided by the refbox
Can we remove this commented out code?

2019-06-26 15:19 UTC, MathewMacDougall commented on src/thunderbots/software/util/parameter/config/ai_control.yaml
> +#        Overrides the friendly goalie id provided by the refbox
fixed

2019-06-27 07:57 UTC, garethellis0 approved these changes

2019-06-27 07:57 UTC, merged