Allow robots to be selected for tactics based on physical capability
UBC-Thunderbots/Software pull request #661
Opened 2019-06-27 08:28 UTC by jordanzliu

## Please fill out the following before requesting review on this PR

### Description

Created an enum of `RobotCapability` for dribbler, kicker, chipper, and a wrapper around `std::bitset` to represent a set of capabilities. 
Added `robotCapabilityRequirements` to `Tactic` with a default implementation of requiring nothing.
Changed tactic cost calculation in `stp.cpp` to set cost to `1.0` if the robot does not have at least the capabilities required by the tactic.

### Testing Done

made some unit tests

### Resolved Issues

Resolves #640 

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [ ] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2019-06-28 04:37 UTC, MathewMacDougall requested changes
This is great so far. Basically exactly what I was thinking of. Aside from the few other comments, it seems that all the robots have no capability by default? Based on the code, this doesn't seem to be the case but I printed in the `createTeamFromROSMessage` function and it said all robots were broken.

2019-06-28 04:37 UTC, MathewMacDougall commented on src/thunderbots/software/ai/util.h
> +    std::stringstream ss(list_str);
Can we be more robust to strings not in csv format? Just logging and moving on is fine, but we don't want a stray character taking down AI (did this during testing)

2019-06-28 04:37 UTC, MathewMacDougall commented on src/thunderbots/software/util/ros_messages.cpp
> +            const std::unordered_set<unsigned int>& broken_dribblers,
The "broken" params are unused

2019-06-28 04:52 UTC, jordanzliu commented on src/thunderbots/software/util/ros_messages.cpp
> +            const std::unordered_set<unsigned int>& broken_dribblers,
removed

2019-06-28 04:53 UTC, jordanzliu commented on src/thunderbots/software/ai/hl/stp/stp.cpp
> +                matrix(row, col) = 1.0f;
done

2019-06-28 05:44 UTC, jordanzliu commented
fixed the thing where it said all robots were broken, turns out i had the signs the wrong way

2019-06-28 05:56 UTC, garethellis0 submitted a review, later dismissed

2019-06-28 06:03 UTC, henryymliu submitted a review, later dismissed
LGTM, nice!

2019-06-29 07:05 UTC, MathewMacDougall approved these changes
LGTM :+1:

2019-06-29 07:39 UTC, merged