Added orientation tolerance to MoveAction and 2 new unit tests
UBC-Thunderbots/Software pull request #694
Opened 2019-07-03 04:28 UTC by EvanMorcom

### Description

Added optional orientation threshold to MoveAction.
The current implementation will set MoveAction as done based solely on the proximity to the destination and ignores the final orientation parameter 

### Testing Done
Added unit tests for new functionality, all existing tests pass.
### Resolved Issues
NA
### Review Checklist
- [X] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [X] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [X] **Remove all commented out code**
- [X] **Remove extra print statements**: for example, those just used for testing
- [X] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [X] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2019-07-03 04:34 UTC, henrymliu commented on src/thunderbots/software/ai/hl/stp/tactic/penalty_kick_tactic.cpp
> +            printf("\nTryingToRotate");
remove?

2019-07-03 04:34 UTC, henrymliu commented on src/thunderbots/software/ai/hl/stp/tactic/penalty_kick_tactic.cpp
> +            printf("\nTryingToMove");
remove?

2019-07-03 04:58 UTC, henryymliu requested changes
couple stray print statements, otherwise LGTM

2019-07-03 07:34 UTC, henryymliu approved these changes

2019-08-12 05:35 UTC, MathewMacDougall commented
@EvanMorcom 	Can this be udpated and merged?

2019-08-24 16:50 UTC, MathewMacDougall commented
@EvanMorcom I think this is good to go once it's updated from `upstream/master`

2019-09-02 18:19 UTC, EvanMorcom commented on src/thunderbots/software/ai/hl/stp/tactic/penalty_kick_tactic.cpp
> +            printf("\nTryingToRotate");
Removed

2019-09-02 18:19 UTC, EvanMorcom commented on src/thunderbots/software/ai/hl/stp/tactic/penalty_kick_tactic.cpp
> +            printf("\nTryingToMove");
Removed

2019-09-03 01:59 UTC, EvanMorcom commented
@MathewMacDougall Good to merge if you want to look it over quickly again.

2019-09-05 23:57 UTC, MathewMacDougall commented
@EvanMorcom 	Ship it :ship:

2019-09-05 23:57 UTC, MathewMacDougall approved these changes

2019-09-06 00:14 UTC, merged