Added Pull Request Template
UBC-Thunderbots/Software pull request #78
Opened 2018-10-04 11:35 UTC by garethellis0

Template is currently just copied from Snowbots.

2018-10-04 20:23 UTC, MathewMacDougall requested changes

2018-10-04 23:54 UTC, garethellis0 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in `src/sample_package` for examples.
Changed to point to the geom folder

2018-10-04 23:54 UTC, garethellis0 commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in `src/sample_package` for examples.
changed to point to the geom folder

2018-10-05 03:10 UTC, MathewMacDougall approved these changes
LGTM

2018-10-05 03:20 UTC, merged