Add PassWithQuality struct encapsulating Pass object and its rating
UBC-Thunderbots/Software pull request #846
Opened 2019-09-28 23:48 UTC by scveloso

### Description

- Added a PassWithQuality struct to encapsulate a Pass object and its rating. 
- Replaced any instance of std::pair<Pass, double> that used to represent a Pass and its rating with this new struct.

### Testing Done

- Old unit tests still pass

### Resolved Issues
resolves #810 

### Misc
Small thing but maybe this struct should be called PassWithRating or the member field could be named quality. Just sticking with the issues' spec here.

2019-09-29 01:24 UTC, MathewMacDougall commented
Good point about the naming, I agree it should be changed. Personally I think renaming the struct `PassWithRating` as you suggested is best, since most other things use "rating" rather than "quality". I also summon @garethellis0 for his opinion since he wrote it originally.

2019-09-29 01:26 UTC, MathewMacDougall requested changes
@scveloso you'll need to fix the formatting on this branch. We use clang-format to auto-format the code for consistency.

You can run the `clang-format/fix_formatting.sh` script. Specifically, running `clang-format/fix_formatting.sh -b master` will compare your changes against your `master` branch and format the diff, which is faster than formatting everything.

2019-09-29 15:26 UTC, garethellis0 commented
I'm fine with either `PassWithRating` or `PassWithQuality`, but I totally agree that we should be consistent.

2019-09-30 07:03 UTC, scveloso commented
Updated the PR changing PassWithQuality -> PassWithRating. 
Also ran the fix formatting script.

2019-09-30 16:51 UTC, MathewMacDougall approved these changes
LGTM :+1:

2019-10-01 21:15 UTC, matthewberends approved these changes
LGTM. Nice job!

2019-10-01 22:20 UTC, jonathanlew approved these changes
LGTM!

2019-10-01 23:49 UTC, garethellis0 approved these changes
LGTM :+1: :tada:

2019-10-02 02:58 UTC, merged