Moved All Evaluation Functions in STP To The AI Level
UBC-Thunderbots/Software pull request #924
Opened 2019-10-12 21:18 UTC by amrm3lm

### Description
Moved all evaluation files from `ai/hl/stp/evaluation` to `ai/evaluation` . 
Added the contents of `ai/hl/stp/evaluation/BUILD` to `ai/evaluation/BUILD`. 
Changed references to `ai/hl/stp/evaluation` functions found in `ai/evaluation/BUILD`, `ai/hl/stp/tactic/BUILD`, and `ai/hl/stp/play/BUILD`. 

### Testing Done
ran `bazel build //...` and build was successful. 
ran `bazel test //...` and all tests passed. 

### Resolved Issues
resolves #795 

### Length Justification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

2019-10-13 00:13 UTC, henryymliu commented
First pass LGTM, but I would like #867 to go through first before this PR; hopefully you won't have to deal with merge conflicts

2019-10-13 04:31 UTC, garethellis0 commented
Gonna give @akhilveeraghanta the first pass for this review.

2019-10-16 15:14 UTC, henryymliu commented
@amrm3lm can you pull from upstream and resolve conflicts?

2019-10-20 01:57 UTC, MathewMacDougall commented
Nice work fixing conflicts. @akhilveeraghanta @henryymliu please review.

2019-10-20 02:52 UTC, henryymliu requested changes
Just one change, everything else LGTM

2019-10-20 02:52 UTC, henryymliu commented on src/software/ai/evaluation/possession.cpp
> +#include "software/ai/evaluation/intercept.h"
Duplicate includes here.

2019-10-20 03:11 UTC, garethellis0 submitted a review, later dismissed
LGTM :+1: :tada: aside from Henry's comment

2019-10-20 03:11 UTC, garethellis0 commented
Oh boy, looks like one file has a merge conflict. :grimacing:

2019-10-21 17:44 UTC, MathewMacDougall commented
Ah looks like more evaluation functions changed (I think from all the RoboCup related changes). @amrm3lm Can you resolve the merge conflicts again :grimacing: ?

2019-10-23 15:43 UTC, akhilveeraghanta submitted a review, later dismissed
Looks Good :tm: after merge conflicts fixed

2019-10-25 02:14 UTC, amrm3lm commented on src/software/ai/evaluation/possession.cpp
> +#include "software/ai/evaluation/intercept.h"
nice spot, I removed them

2019-10-25 15:23 UTC, MathewMacDougall approved these changes
LGTM :+1: Thanks for persevering through the conflicts

2019-10-25 15:23 UTC, MathewMacDougall approved these changes
LGTM :+1: Thanks for persevering through the conflicts

2019-10-25 15:24 UTC, MathewMacDougall commented
@henryymliu will need your re-approval

2019-10-25 15:26 UTC, akhilveeraghanta approved these changes
Looks Good :tm:

2019-10-25 16:19 UTC, henryymliu approved these changes
🚢🤡

2019-10-25 18:23 UTC, merged